// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 *         resource_type: "monitor",
 *         resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4"
 *     }
 */
export interface AssignWebhookResourceRequestDto {
    /** Unique webhook identifier. */
    webhook_id: string;
    /** Type of resource to assign. */
    resource_type: CatchAllApi.MappableResourceType;
    /** ID of the resource to assign. */
    resource_id: string;
}
