// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListWebhooksRequest {
    /** Page number to retrieve. */
    page?: number;
    /** Number of webhooks per page. */
    page_size?: number;
    /** Filter results by text (case-insensitive substring match). */
    search?: string;
}
