// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
 *     }
 */
export interface ListWebhookResourcesRequest {
    /** Unique webhook identifier. */
    webhook_id: string;
    resource_type?: CatchAllApi.MappableResourceType;
    /** Page number to retrieve. */
    page?: number;
    /** Number of assignments per page. */
    page_size?: number;
}
