// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         resource_type: "job",
 *         resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4"
 *     }
 */
export interface ListWebhooksForResourceRequest {
    resource_type: CatchAllApi.MappableResourceType;
    /** Unique resource identifier. */
    resource_id: string;
    /** Filter by active status. Omit to return webhooks regardless of status. */
    is_active?: boolean;
    /** Page number to retrieve. */
    page?: number;
    /** Number of webhooks per page. */
    page_size?: number;
}
