// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 *         payload: {
 *             "test": true,
 *             "message": "CatchAll webhook test"
 *         }
 *     }
 */
export interface TestWebhookRequestDto {
    /** Unique webhook identifier. */
    webhook_id: string;
    /**
     * Custom payload to send in the test request. If omitted, a synthetic
     * test payload is sent.
     */
    payload?: Record<string, unknown>;
}
