// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         resource_type: "job",
 *         resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
 *         webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
 *         job_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4"
 *     }
 */
export interface TriggerWebhookRequest {
    resource_type: CatchAllApi.MappableResourceType;
    /** Unique resource identifier. */
    resource_id: string;
    /** Identifier of the webhook to trigger. Must be assigned to the resource. */
    webhook_id: string;
    /**
     * Specific job run to deliver. Optional for `job` resources; for
     * `monitor` and `monitor_group` resources, selects a past run to replay.
     * When omitted, the latest available results are delivered.
     */
    job_id?: string;
}
