// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         job_id: "5f0c9087-85cb-4917-b3c7-e5a5eff73a0c"
 *     }
 */
export interface DeleteJobRequest {
    /** Unique job identifier returned from [`POST /catchAll/submit`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/create-job). */
    job_id: string;
}
