// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3"
 *     }
 */
export interface GetJobStatusRequest {
    /** Unique job identifier returned from the `/catchAll/submit` endpoint. */
    job_id: string;
}
