// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         job_id: "job_id"
 *     }
 */
export interface GetJobResultsCsvRequest {
    /** Unique job identifier returned from [`POST /catchAll/submit`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/create-job). */
    job_id: string;
}
