// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetUserJobsRequest {
    /** Page number to retrieve. */
    page?: number;
    /** Number of records per page. */
    page_size?: number;
}
