// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetUserJobsRequest {
    /** Page number to retrieve. */
    page?: number;
    /** Number of records per page. */
    page_size?: number;
    /** Filter results by text (case-insensitive substring match). */
    search?: string;
    /** Filter results by ownership. Defaults to `all`. */
    ownership?: CatchAllApi.OwnershipFilter;
}
