// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "Series B funding rounds for SaaS startups",
 *         context: "Focus on funding amount and company name"
 *     }
 */
export interface InitializeRequestDto {
    query: CatchAllApi.Query;
    context?: CatchAllApi.Context;
}
