// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "AI company acquisitions in fintech last week"
 *     }
 */
export interface InitializeRequestDto {
    query: CatchAllApi.Query;
    context?: CatchAllApi.Context;
}
