// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSourceGroupsRequest {
    /** Page number to retrieve. */
    page?: number;
    /** Number of source groups per page. */
    page_size?: number;
}
