// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "Series B funding rounds for SaaS startups",
 *         context: "Focus on funding amount and company name",
 *         limit: 10,
 *         start_date: "2026-02-18T00:00:00Z",
 *         end_date: "2026-02-23T00:00:00Z",
 *         mode: "base"
 *     }
 */
export interface SubmitRequestDto {
    query: CatchAllApi.Query;
    context?: CatchAllApi.Context;
    limit?: CatchAllApi.Limit;
    start_date?: CatchAllApi.StartDate;
    end_date?: CatchAllApi.EndDate;
    /**
     * Custom validators for filtering web page clusters.
     *
     * If not provided, validators are generated automatically based on the query.
     */
    validators?: CatchAllApi.ValidatorSchema[];
    /**
     * Custom enrichment fields for data extraction.
     *
     * If not provided, enrichments are generated automatically based on the query.
     */
    enrichments?: CatchAllApi.EnrichmentSchema[];
    /**
     * Job processing mode.
     *
     * - `base`: Full pipeline with validation and enrichment.
     * - `lite`: Lightweight extraction with faster processing. Returns titles and citations only.
     */
    mode?: SubmitRequestDto.Mode;
}

export namespace SubmitRequestDto {
    /**
     * Job processing mode.
     *
     * - `base`: Full pipeline with validation and enrichment.
     * - `lite`: Lightweight extraction with faster processing. Returns titles and citations only.
     */
    export const Mode = {
        Lite: "lite",
        Base: "base",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
