// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "Series B funding rounds for SaaS startups",
 *         context: "Focus on funding amount and company name",
 *         limit: 10,
 *         start_date: "2026-02-18T00:00:00Z",
 *         end_date: "2026-02-23T00:00:00Z",
 *         mode: "base"
 *     }
 */
export interface SubmitRequestDto {
    query: CatchAllApi.Query;
    context?: CatchAllApi.Context;
    limit?: CatchAllApi.Limit;
    start_date?: CatchAllApi.StartDate;
    end_date?: CatchAllApi.EndDate;
    /**
     * Custom validators for filtering web page clusters.
     *
     * If not provided, validators are generated automatically based on the query.
     */
    validators?: CatchAllApi.ValidatorSchema[];
    /**
     * Custom enrichment fields for data extraction.
     *
     * If not provided, enrichments are generated automatically based on the query.
     */
    enrichments?: CatchAllApi.EnrichmentSchema[];
    /**
     * Job processing mode.
     *
     * - `base`: Full pipeline with validation and enrichment.
     * - `lite`: Lightweight extraction with faster processing. Returns titles and citations only.
     */
    mode?: SubmitRequestDto.Mode;
    /**
     * Dataset IDs to connect to the job. When provided, this enables Company Watchlist mode — the job returns only events relevant to companies in the connected datasets. To set the minimum relevance threshold, use `ed_score_min`.
     *
     * The dataset must have `latest_status: ready` before the job is submitted. Submitting with a non-existent or inaccessible dataset ID returns `400`.
     */
    connected_dataset_ids?: string[];
    /**
     * The minimum relevance score a connected entity must reach for its record to be included in results.
     *
     * Only valid when `connected_dataset_ids` is set; otherwise ignored. Records where no connected entity meets the threshold are excluded entirely.
     */
    ed_score_min?: number;
    /** Project to assign this job to. The job appears in the project's resource list immediately after submission. */
    project_id?: string;
    /** IDs of webhooks to notify when the job completes. Maximum 5 per job. */
    webhook_ids?: string[];
    /**
     * When true, retrieves all news for connected Company Watchlist entities
     * without topic filtering. Requires connected_dataset_ids to be set.
     */
    fetch_all_watchlist_news?: boolean;
    /**
     * Filter events by entity association type. `event_associated` keeps only
     * events where the entity is a direct actor. `mention` keeps only events
     * where the entity is merely referenced. Only relevant when
     * connected_dataset_ids is set.
     */
    ed_association_type?: CatchAllApi.EntityAssociationType;
}

export namespace SubmitRequestDto {
    /**
     * Job processing mode.
     *
     * - `base`: Full pipeline with validation and enrichment.
     * - `lite`: Lightweight extraction with faster processing. Returns titles and citations only.
     */
    export const Mode = {
        Lite: "lite",
        Base: "base",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
