// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         query: "AI company acquisitions",
 *         context: "Focus on deal size and acquiring company details"
 *     }
 */
export interface SubmitRequestDto {
    query: CatchAllApi.Query;
    schema?: CatchAllApi.Schema;
    context?: CatchAllApi.Context;
    /**
     * Maximum number of records to return. If not specified, defaults to your plan limit.
     *
     * Use /catchAll/continue to extend the limit after job completion without reprocessing.
     */
    limit?: number;
}
