// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         query: "Series B funding rounds for SaaS startups"
 *     }
 */
export interface ValidateQueryRequestDto {
    /** Plain text query to validate. */
    query: string;
}
