// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         entities: [{
 *                 name: "OpenAI",
 *                 entity_type: "company",
 *                 description: "Artificial intelligence research company",
 *                 additional_attributes: {
 *                     company_attributes: {
 *                         domain: "openai.com",
 *                         key_persons: ["Sam Altman"],
 *                         alternative_names: ["Open AI"]
 *                     }
 *                 }
 *             }, {
 *                 name: "Stripe",
 *                 entity_type: "company",
 *                 description: "Online payment processing platform",
 *                 additional_attributes: {
 *                     company_attributes: {
 *                         domain: "stripe.com",
 *                         key_persons: ["Patrick Collison", "John Collison"]
 *                     }
 *                 }
 *             }]
 *     }
 */
export interface CreateEntitiesBatchRequest {
    /**
     * Array of entities to create. Each item follows the same schema
     * as single entity creation.
     */
    entities: CatchAllApi.CreateEntityRequest[];
}
