// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entity_id: "854198fa-f702-49db-a381-0427fa87f173"
 *     }
 */
export interface GetEntityRequest {
    /** Unique entity identifier. */
    entity_id: string;
}
