// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         search: "NewsCatcher"
 *     }
 */
export interface ListEntitiesRequest {
    /** Page number to retrieve. */
    page?: number;
    /** Number of entities per page. */
    page_size?: number;
    /** Filter entities by name (case-insensitive substring match). */
    search?: string;
    status?: CatchAllApi.EntityStatus;
    entity_type?: CatchAllApi.EntityType;
    sort_by?: CatchAllApi.EntitySortBy;
    sort_order?: CatchAllApi.SortOrder;
}
