// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         search: "NewsCatcher",
 *         project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04"
 *     }
 */
export interface ListEntitiesRequest {
    /** Page number to retrieve. */
    page?: number;
    /** Number of entities per page. */
    page_size?: number;
    /** Filter entities by name (case-insensitive substring match). */
    search?: string;
    status?: CatchAllApi.EntityStatus;
    entity_type?: CatchAllApi.EntityType;
    sort_by?: CatchAllApi.EntitySortBy;
    sort_order?: CatchAllApi.SortOrder;
    /** Filter results to resources belonging to this project. */
    project_id?: string;
}
