// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         entity_id: "854198fa-f702-49db-a381-0427fa87f173",
 *         description: "Updated description",
 *         additional_attributes: {
 *             company_attributes: {
 *                 alternative_names: ["NC", "NewsCatcher API", "NCA"]
 *             }
 *         }
 *     }
 */
export interface UpdateEntityRequest {
    /** Unique entity identifier. */
    entity_id: string;
    /** Updated entity name. */
    name?: string;
    /** Updated description. */
    description?: string;
    additional_attributes?: CatchAllApi.AdditionalAttributes;
}
