// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04"
 *     }
 */
export interface ListMonitorsRequest {
    /** Page number to retrieve. */
    page?: number;
    /** Number of records per page. */
    page_size?: number;
    /** Filter results by text (case-insensitive substring match). */
    search?: string;
    ownership?: CatchAllApi.OwnershipFilter;
    /** Filter results to resources belonging to this project. */
    project_id?: string;
}
