// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         monitor_id: "monitor_id",
 *         webhook_ids: ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"]
 *     }
 *
 * @example
 *     {
 *         monitor_id: "monitor_id",
 *         schedule: "every Monday at 9 AM",
 *         timezone: "America/New_York"
 *     }
 */
export interface UpdateMonitorRequestDto {
    /** Event monitor identifier. */
    monitor_id: string;
    /**
     * Updated list of centralized webhook IDs for this event monitor.
     *
     * Replaces all existing webhook assignments. Pass an empty array `[]` to clear all assignments. Omit to leave existing assignments unchanged.
     */
    webhook_ids?: string[];
    /** Updated maximum number of records per event monitor run. */
    limit?: number;
    /**
     * New natural-language schedule that replaces the event monitor's current
     * schedule. Examples: `every day at 9 AM`, `every Monday at 6 PM EST`.
     *
     * Omit to keep the current schedule. The new schedule takes effect from the
     * next scheduler reload, and the old schedule stops firing. Returns `422` if
     * the text can't be parsed or runs would be spaced too closely.
     */
    schedule?: string | null;
    /**
     * IANA timezone for the new schedule (for example, `America/New_York`).
     * A timezone included in the `schedule` text takes precedence. Ignored if
     * `schedule` is not set.
     */
    timezone?: string | null;
}
