// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
 *         resources: [{
 *                 resource_type: "job",
 *                 resource_id: "48421e16-1f50-4048-b62c-d3bc0789d30d"
 *             }]
 *     }
 */
export interface AddResourceRequestDto {
    /** Unique project identifier. */
    project_id: string;
    /** Resources to assign to the project. */
    resources: CatchAllApi.ResourceItemDto[];
}
