// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04"
 *     }
 */
export interface DeleteProjectRequest {
    /** Unique project identifier. */
    project_id: string;
    /**
     * If true, permanently deletes all resources (jobs, monitors, datasets, monitor groups) assigned to the project. If false, the project is deleted and its resources are unassigned but not deleted.
     *
     * Webhooks are never deleted by either setting — they are only detached from the project.
     */
    delete_resources?: boolean;
}
