// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04"
 *     }
 */
export interface GetProjectRequest {
    /** Unique project identifier. */
    project_id: string;
}
