// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04"
 *     }
 */
export interface ListProjectResourcesRequest {
    /** Unique project identifier. */
    project_id: string;
    resource_type?: CatchAllApi.ProjectResourceType;
    /** Page number to retrieve. */
    page?: number;
    /** Number of records per page. */
    page_size?: number;
}
