// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         reference_job_id: "5f0c9087-85cb-4917-b3c7-e5a5eff73a0c",
 *         schedule: "every day at 12 PM",
 *         timezone: "UTC",
 *         webhook_ids: ["a1b2c3d4-e5f6-7890-abcd-ef1234567890"],
 *         limit: 10,
 *         backfill: true
 *     }
 */
export interface CreateMonitorRequestDto {
    /**
     * Job ID to use as template for scheduled runs. Defines the query, validators, and enrichments used for each scheduled run.
     *
     * If [`backfill`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/monitors/create-monitor#body-backfill) is true, the job's `end_date` must be within the last 7 days.
     */
    reference_job_id: string;
    /** Monitor schedule in plain text format. Minimum frequency depends on your plan. */
    schedule: string;
    /**
     * The IANA timezone identifier used as the fallback when the `schedule` string does not include an explicit timezone.
     *
     * If the schedule includes a timezone abbreviation (for example, `"every day at 9am EST"`), the parsed timezone takes priority and this value is ignored.
     */
    timezone?: string;
    /**
     * IDs of centralized webhooks to notify on each run completion.
     * Passing IDs here is equivalent to calling
     * `POST /catchAll/webhooks/{webhook_id}/resources` for each ID after creation.
     * Maximum 5 per monitor.
     */
    webhook_ids?: string[];
    /** Maximum number of records per monitor run. If not provided, defaults to the plan limit. */
    limit?: number;
    /**
     * If true, fills the data gap between the reference job's `end_date` and the first scheduled run. The reference job's `end_date` must be within the last 7 days.
     *
     * If false, no gap filling occurs and the first run uses the current cron window only — the reference job's age does not matter.
     */
    backfill?: boolean;
    /** Project to assign this monitor to. The monitor appears in the project's resource list after creation. */
    project_id?: string;
}
