// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         reference_job_id: "reference_job_id",
 *         schedule: "every day at 12 PM UTC"
 *     }
 */
export interface CreateMonitorRequestDto {
    /** Job ID to use as template for scheduled runs. */
    reference_job_id: string;
    /**
     * Natural language schedule (e.g. 'every day at 12 AM EST').
     *
     * **Minimum frequency:** Monitors must be scheduled at least 24 hours apart.
     */
    schedule: string;
    /** Optional webhook to receive notifications when jobs complete. */
    webhook?: CatchAllApi.WebhookDto;
}
