// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         monitor_id: "monitor_id"
 *     }
 */
export interface DeleteMonitorRequest {
    /** Monitor identifier. */
    monitor_id: string;
}
