// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         monitor_id: "monitor_id",
 *         backfill: true
 *     }
 */
export interface EnableMonitorRequestDto {
    /** Monitor identifier. */
    monitor_id: string;
    /**
     * If true, fills the data gap between the last job's `end_date` and the first scheduled run after enabling. The last job's `end_date` must be within the last 7 days.
     *
     * If false, no gap filling occurs and the first run uses the current cron window only — the last job's age does not matter.
     */
    backfill?: boolean;
}
