// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         monitor_id: "monitor_id"
 *     }
 */
export interface ListMonitorJobsRequest {
    /** Monitor identifier. */
    monitor_id: string;
    /** Sort by start_date (asc or desc). */
    sort?: CatchAllApi.ListMonitorJobsRequestSort;
}
