// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../../index.js";

/**
 * @example
 *     {
 *         monitor_id: "monitor_id",
 *         webhook: {
 *             url: "https://new-endpoint.com/webhook",
 *             method: "POST",
 *             headers: {
 *                 "Authorization": "Bearer new_token_xyz"
 *             }
 *         }
 *     }
 */
export interface UpdateMonitorRequestDto {
    /** Monitor identifier. */
    monitor_id: string;
    /** Updated webhook configuration. */
    webhook?: CatchAllApi.WebhookDto;
}
