// This file was auto-generated by Fern from our API Definition.

/**
 * API key authentication as returned in webhook responses. The key value is masked.
 */
export interface ApiKeyAuthResponseDto {
    /** HTTP header name for the API key. Returned in full. */
    header?: (string | null) | undefined;
    /** Masked API key value. Never returned in full. */
    value?: (string | null) | undefined;
}
