// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface AssignWebhookResourceResponseDto {
    /** True if the operation succeeded; false otherwise. */
    success: boolean;
    /** Human-readable result message. */
    message?: string | undefined;
    /** True if the assignment already existed before this request. */
    already_existed?: boolean | undefined;
    /** The created or existing resource mapping. */
    mapping?: CatchAllApi.WebhookResourceMappingResponseDto | undefined;
}
