// This file was auto-generated by Fern from our API Definition.

export interface BaseRecord {
    /** Unique identifier for the record. */
    record_id: string;
    /** Short title summarizing the record. */
    record_title: string;
    /**
     * Structured data extracted from web pages. Schema is dynamically generated per job. Field names are chosen semantically to match the content.
     *
     * **Note:** The system always includes the `enrichment_confidence` field within the `enrichment` object, regardless of whether enrichments are generated or specified by you.
     *
     *  For integration guidance, see [Dynamic schemas](https://www.newscatcherapi.com/docs/web-search-api/guides-and-concepts/dynamic-schemas)
     */
    enrichment: BaseRecord.Enrichment;
}

export namespace BaseRecord {
    /**
     * Structured data extracted from web pages. Schema is dynamically generated per job. Field names are chosen semantically to match the content.
     *
     * **Note:** The system always includes the `enrichment_confidence` field within the `enrichment` object, regardless of whether enrichments are generated or specified by you.
     *
     *  For integration guidance, see [Dynamic schemas](https://www.newscatcherapi.com/docs/web-search-api/guides-and-concepts/dynamic-schemas)
     */
    export interface Enrichment {
        /** Overall confidence score for the enrichment extraction. */
        enrichment_confidence?: (Enrichment.EnrichmentConfidence | null) | undefined;
        /** Accepts any additional properties */
        [key: string]: any;
    }

    export namespace Enrichment {
        /** Overall confidence score for the enrichment extraction. */
        export const EnrichmentConfidence = {
            Low: "low",
            Medium: "medium",
            High: "high",
        } as const;
        export type EnrichmentConfidence = (typeof EnrichmentConfidence)[keyof typeof EnrichmentConfidence];
    }
}
