// This file was auto-generated by Fern from our API Definition.

/**
 * Basic authentication as returned in webhook responses. The password is masked.
 */
export interface BasicAuthResponseDto {
    /** Basic auth username. Returned in full. */
    username?: (string | null) | undefined;
    /** Masked password. Never returned in full. */
    password?: (string | null) | undefined;
}
