// This file was auto-generated by Fern from our API Definition.

export interface Citation {
    /** Article title */
    title: string;
    /** URL to the source article */
    link: string;
    /** Article publication date in ISO 8601 format with UTC timezone. */
    published_date: string;
}
