// This file was auto-generated by Fern from our API Definition.

export interface Citation {
    /** The title of the source document. */
    title: string;
    /** URL to the source document. */
    link: string;
    /** The publication date of the source document in ISO 8601 format (UTC timezone). */
    published_date: string;
}
