// This file was auto-generated by Fern from our API Definition.

/**
 * Identifying attributes for a company entity. All fields are optional but improve matching quality.
 */
export interface CompanyAttributes {
    /**
     * Company website domain without protocol or trailing slash.
     *
     * The most reliable identifier — strongly recommended when available.
     */
    domain?: (string | null) | undefined;
    /** Detailed description of the company used for matching. */
    description?: (string | null) | undefined;
    /** Names of key people associated with the company (founders, executives, etc.). Improves matching for articles that mention people rather than the company name. */
    key_persons?: (string[] | null) | undefined;
    /** Alternative names, abbreviations, or aliases. Helps resolve common variations of the company name. */
    alternative_names?: (string[] | null) | undefined;
}
