// This file was auto-generated by Fern from our API Definition.

/**
 * A dataset used to narrow the retrieval scope of a job or monitor, returned with its identifier and name.
 */
export interface ConnectedDataset {
    /** Dataset identifier. */
    id: string;
    /** Dataset name as stored. Check `is_deleted` to determine whether the dataset is still active. */
    name: string;
    /** True when the dataset has been deleted. */
    is_deleted?: boolean | undefined;
}
