// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * A company entity matched to a record in a Company Watchlist job, with a relevance score and explanation.
 *
 * Only entities with `ed_score` ≥ 1 appear in results. Entities scored 0 are filtered out before the response is returned. When `ed_score_min` is set at submission time, entities below that threshold are excluded.
 */
export interface ConnectedEntity {
    /** Unique identifier of the matched entity. */
    entity_id: string;
    /** Name of the matched entity. */
    name: string;
    /**
     * Relevance score indicating how directly the entity is associated with this event.
     *
     * | Score | Meaning |
     * |-------|---------|
     * | 10 | Direct mention, critical event (merger, CEO change, major lawsuit) |
     * | 7–9 | Major impact (earnings, product launch, senior hire) |
     * | 4–6 | Routine update (minor product news, mid-level changes) |
     * | 1–3 | Indirect mention (listed with others, stock noise) |
     */
    ed_score: number;
    /** Short explanation (up to 100 characters) of why this entity is associated with the event. */
    relation: string;
    /** The entity type. */
    type: string;
    /**
     * The stored attributes for this entity. Present only when attributes exist in the database.
     *
     * The field name matches the value of `type` — for example, `"company"` type entities have a `company`  field.
     */
    company?: CatchAllApi.CompanyAttributes | undefined;
}
