// This file was auto-generated by Fern from our API Definition.

export interface ContinueResponseDto {
    /** Job identifier for the continued job. */
    job_id: string;
    /** Previous record limit before continuation. */
    previous_limit?: number;
    /** New record limit after continuation. */
    new_limit: number;
    /** Confirmation that the continuation request was accepted. */
    status?: string;
}
