// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface CreateWebhookResponseDto {
    /** True if the webhook was created; false otherwise. */
    success: boolean;
    /** Human-readable result message. */
    message: string;
    /** The created webhook object. */
    webhook?: CatchAllApi.WebhookResponseDto | undefined;
}
