// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * Request body for creating a single entity. Only `name` is required.
 * The more fields you provide, the better the matching quality.
 */
export interface CreateEntityRequest {
    /** The company or person name. Required and must be non-empty. */
    name: string;
    entity_type?: CatchAllApi.EntityType | undefined;
    /** Free-text description of the entity used for disambiguation when similar names exist. */
    description?: string | undefined;
    additional_attributes?: CatchAllApi.AdditionalAttributes | undefined;
}
