// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface CreateEntitiesBatchResponse {
    /** Array of created entity stubs in the same order as the input. */
    entities: CatchAllApi.CreateEntityResponse[];
    /** Total number of entities created. */
    count: number;
}
