// This file was auto-generated by Fern from our API Definition.

export interface CreateEntityResponse {
    /** Unique identifier of the created entity. */
    id: string;
    /** Initial status of the entity. Always `pending` immediately after creation — enrichment happens asynchronously. */
    status: string;
}
