// This file was auto-generated by Fern from our API Definition.

export interface CreateProjectResponseDto {
    /** True if the operation succeeded; false otherwise. */
    success: boolean;
    /** Human-readable result message. */
    message: string;
    /** Project identifier. */
    project_id: string;
    /** Name of the created project. */
    name: string;
}
