// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface DatasetEntityListResponse {
    /** Array of entity summary objects for this page. */
    entities: CatchAllApi.EntitySummary[];
    /** Total number of entities in the dataset. */
    total: number;
    /** Current page number. */
    page: number;
    /** Number of entities per page. */
    page_size: number;
}
