// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface DatasetResponse {
    /** Unique identifier of the dataset. */
    id: string;
    /** Organization that owns this dataset. */
    organization_id: string;
    /** Dataset name. */
    name: string;
    /** Optional description. */
    description?: (string | null) | undefined;
    /** Total number of entities in this dataset. */
    entity_count?: number | undefined;
    latest_status?: CatchAllApi.DatasetStatus | undefined;
    /** ID of the user who created this dataset. */
    created_by_user_id?: string | undefined;
    /** ISO 8601 timestamp of when the dataset was created. Returned without timezone offset (server-local time). */
    created_at?: string | undefined;
    /** ISO 8601 timestamp of when the dataset was last updated. Returned without timezone offset (server-local time). */
    updated_at?: string | undefined;
}
