// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * A single status change event in a dataset's history.
 */
export interface DatasetStatusEntry {
    status: CatchAllApi.DatasetStatus;
    /** Additional context about the status change, if available. */
    additional_information?: (Record<string, unknown> | null) | undefined;
    /** ISO 8601 timestamp of when this status was set. Returned without timezone offset (server-local time). */
    created_at?: string | undefined;
}
