// This file was auto-generated by Fern from our API Definition.

export interface DeleteJobResponseDto {
    /** True if the delete operation succeeded; false otherwise. */
    success: boolean;
    /** Human-readable result message. */
    message: string | null;
    /** ID of the deleted job. `null` on failure. */
    job_id: string | null;
}
