// This file was auto-generated by Fern from our API Definition.

export interface DeleteMonitorResponseDto {
    /** Whether the delete operation succeeded. */
    success: boolean;
    /** Human-readable result message. */
    message: string | null;
    /** ID of the deleted monitor. `null` on failure. */
    monitor_id: string | null;
}
