// This file was auto-generated by Fern from our API Definition.

/** Outcome of a webhook delivery attempt. */
export const DeliveryStatus = {
    Success: "SUCCESS",
    Failed: "FAILED",
} as const;
export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus];
