// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * Schema for a single enrichment field that extracts structured data.
 *
 * Enrichments are applied during the enriching stage to extract information from validated clusters.
 */
export interface EnrichmentSchema {
    /** Enrichment field name (snake_case recommended). */
    name: string;
    /** What information this field extracts. */
    description: string;
    type: CatchAllApi.EnrichmentType;
}
