// This file was auto-generated by Fern from our API Definition.

/**
 * Canonical enrichment types supported by the system.
 *
 * - `text`: Free-form text strings (names, descriptions, summaries)
 * - `number`: Numeric values (amounts, counts, percentages)
 * - `date`: ISO format dates (YYYY-MM-DD)
 * - `option`: Enum-like fixed values (status, category)
 * - `url`: Web URLs
 * - `company`: Structured company data. Returns `source_text`, `confidence`, and `metadata`. See [Company enrichment](https://www.newscatcherapi.com/docs/web-search-api/api-reference/jobs/company-enrichment-dto) data model.
 */
export const EnrichmentType = {
    Text: "text",
    Number: "number",
    Date: "date",
    Option: "option",
    Url: "url",
    Company: "company",
} as const;
export type EnrichmentType = (typeof EnrichmentType)[keyof typeof EnrichmentType];
