// This file was auto-generated by Fern from our API Definition.

/**
 * Canonical enrichment types supported by the system.
 *
 * - `text`: Free-form text strings (names, descriptions, summaries)
 * - `number`: Numeric values (amounts, counts, percentages)
 * - `date`: ISO format dates (YYYY-MM-DD)
 * - `option`: Enum-like fixed values (status, category)
 * - `url`: Web URLs
 * - `dict`: Complex structured objects
 * - `company`: Structured company data (name, alternative_names, website_candidates, people, address)
 */
export const EnrichmentType = {
    Text: "text",
    Number: "number",
    Date: "date",
    Option: "option",
    Url: "url",
    Dict: "dict",
    Company: "company",
} as const;
export type EnrichmentType = (typeof EnrichmentType)[keyof typeof EnrichmentType];
