// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface EntityListResponse {
    /** Array of entity objects for this page. */
    entities: CatchAllApi.EntityResponse[];
    /** Total number of entities matching the filter criteria. */
    total: number;
    /** Current page number. */
    page: number;
    /** Number of entities per page. */
    page_size: number;
}
