// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface EntityResponse {
    /** Unique identifier of the entity. */
    id: string;
    entity_type: CatchAllApi.EntityType;
    /** Organization that owns this entity. */
    organization_id: string;
    /** Entity name. */
    name: string;
    /** Free-text description. */
    description?: (string | null) | undefined;
    additional_attributes?: CatchAllApi.AdditionalAttributes | undefined;
    status: CatchAllApi.EntityStatus;
    /** ID of the user who created this entity. */
    created_by_user_id?: string | undefined;
    /** ISO 8601 timestamp of when the entity was created. Returned without timezone offset (server-local time). */
    created_at?: string | undefined;
    /** ISO 8601 timestamp of when the entity was last updated. Returned without timezone offset (server-local time). */
    updated_at?: string | undefined;
}
