// This file was auto-generated by Fern from our API Definition.

/** Fields available for sorting entity list results. */
export const EntitySortBy = {
    CreatedAt: "created_at",
    Name: "name",
    Status: "status",
} as const;
export type EntitySortBy = (typeof EntitySortBy)[keyof typeof EntitySortBy];
