// This file was auto-generated by Fern from our API Definition.

/**
 * How an entity relates to an event.
 *
 * - `event_associated`: The entity is a direct actor in the event (primary subject).
 * - `mention`: The entity is merely referenced in passing.
 */
export const EntityAssociationType = {
    Mention: "mention",
    EventAssociated: "event_associated",
} as const;
export type EntityAssociationType = (typeof EntityAssociationType)[keyof typeof EntityAssociationType];
