// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * Abbreviated entity object returned when listing entities within a
 * dataset. Uses a flat `attributes` key rather than the nested
 * `additional_attributes.company_attributes` structure used in
 * standalone entity endpoints.
 */
export interface EntitySummary {
    /** Unique identifier of the entity. */
    id: string;
    /** Entity name. */
    name: string;
    entity_type: CatchAllApi.EntityType;
    status: CatchAllApi.EntityStatus;
    /** Free-text description. */
    description?: (string | null) | undefined;
    attributes?: CatchAllApi.CompanyAttributes | undefined;
}
