// This file was auto-generated by Fern from our API Definition.

/**
 * Fixed-taxonomy classification of the event described by a record.
 *
 * Tagging is additive: it never filters or removes records. A record the classifier
 * cannot place is still returned, with `unclassifiable` or `other_sector` in place of
 * a taxonomy value.
 */
export interface EventTags {
    /**
     * Taxonomy path describing what happened, drawn from a fixed vocabulary.
     * `unclassifiable` when no path fits.
     */
    event_type?: (string | null) | undefined;
    /**
     * Industry sector the event belongs to, drawn from a fixed vocabulary.
     * `other_sector` when no sector fits.
     */
    sector?: (string | null) | undefined;
}
