// This file was auto-generated by Fern from our API Definition.

/**
 * Custom payload formatter for `custom` webhooks. A Liquid template is
 * rendered at dispatch time to build a fully tailored request body — trim or
 * rename fields, apply conditional logic, or emit non-JSON formats.
 */
export interface FormatterConfigDto {
    /** Liquid template string rendered at dispatch time. Maximum 10 KB. */
    template: string;
    /**
     * Content-Type of the rendered output. Supported values: `application/json`,
     * `application/ld+json`, `text/html`, `text/plain`, `text/xml`,
     * `application/xml`, `text/csv`.
     */
    content_type?: string | undefined;
}
