// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface GetPlanLimitsResponseDto {
    /** Plan features with current usage. */
    features: CatchAllApi.PlanFeature[];
}
