// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface GetWebhookResponseDto {
    /** True if the operation succeeded; false otherwise. */
    success: boolean;
    /** Human-readable result message. */
    message: string;
    /** The retrieved webhook object. */
    webhook?: CatchAllApi.WebhookResponseDto | undefined;
}
