// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * Suggestions for validators, enrichments, and date ranges based on query analysis.
 *
 * Date ranges are validated against plan limits and adjusted if necessary.
 */
export interface InitializeResponseDto {
    /** Suggested validators for filtering relevant articles. */
    validators: CatchAllApi.ValidatorSchema[];
    /** Suggested enrichment fields for data extraction. */
    enrichments: CatchAllApi.EnrichmentSchema[];
    start_date: CatchAllApi.StartDate;
    end_date: CatchAllApi.EndDate;
    /**
     * Messages explaining date adjustments due to plan limits.
     *
     * Empty array if no modifications were needed. Contains human-readable messages when requested dates exceed plan's allowed lookback period.
     */
    date_modification_message?: string[];
}
