// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface JobStep {
    status: CatchAllApi.JobStatus;
    /** Sequential position of this step in the pipeline (1-7). */
    order: number;
    /** Whether this step has finished processing. */
    completed?: boolean;
}
