// This file was auto-generated by Fern from our API Definition.

/**
 * Current job processing status. Jobs progress through these stages:
 *
 * - `submitted`: Job queued, waiting to start processing.
 * - `analyzing`: Extracting keywords, generating search queries, and creating validators/extractors.
 * - `fetching`: Retrieving articles from web sources.
 * - `clustering`: Grouping similar articles into distinct events.
 * - `enriching`: Validating clusters and extracting structured data.
 * - `completed`: Job finished successfully, results ready.
 * - `failed`: Job processing failed.
 *
 * Poll `/catchAll/status/{job_id}` every 30-60 seconds until status is `completed` (typically 10-15 minutes).
 */
export const JobStatus = {
    Submitted: "submitted",
    Analyzing: "analyzing",
    Fetching: "fetching",
    Clustering: "clustering",
    Enriching: "enriching",
    Completed: "completed",
    Failed: "failed",
} as const;
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];
