// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ListWebhooksResponseDto {
    /** Total number of webhooks in the organization. */
    total: number;
    /** Current page number. */
    page: number;
    /** Number of webhooks per page. */
    page_size: number;
    /** Total number of pages available. */
    total_pages: number;
    /** Webhooks on this page. */
    webhooks: CatchAllApi.WebhookResponseDto[];
}
