// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ListWebhookResourcesResponseDto {
    /** Total number of resource mappings for this webhook. */
    total: number;
    /** Current page number. */
    page: number;
    /** Number of mappings per page. */
    page_size: number;
    /** Total number of pages available. */
    total_pages: number;
    /** Resource mappings on this page. */
    resources: CatchAllApi.WebhookResourceMappingResponseDto[];
}
