// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ListMonitorsResponseDto {
    /** Total number of event monitors for this user. */
    total: number;
    /** Current page number. */
    page: number;
    /** Number of event monitors per page. */
    page_size: number;
    /** Total number of pages available. */
    total_pages: number;
    /** Array of event monitor summaries. */
    monitors: CatchAllApi.MonitorListItemDto[];
}
