// This file was auto-generated by Fern from our API Definition.

export interface ListUserJobsResponseDto {
    /** Job identifier. */
    job_id: string;
    /** The natural language query for this job. */
    query: string;
    /** Job creation timestamp in ISO 8601 format. */
    created_at: string;
    /** Current processing status of the job. */
    status: string;
}
