// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ListMonitorsResponseDto {
    /** Total number of monitors for this user. */
    total_monitors: number;
    /** Array of monitor summaries. */
    monitors: CatchAllApi.MonitorListItemDto[];
}
