// This file was auto-generated by Fern from our API Definition.

export interface ManageEntitiesResponse {
    /** ID of the dataset that was modified. */
    dataset_id: string;
    /** Number of entities that were added or removed. */
    affected_count: number;
}
