// This file was auto-generated by Fern from our API Definition.

/**
 * Citation with monitor-specific metadata. Used in monitor results and webhook payloads.
 * Extends base citation with tracking information for job_id and timestamps.
 */
export interface MonitorCitation {
    /** Article identifier from News API v3 */
    id: string;
    /** Article title */
    title: string;
    /** URL to the source article */
    link: string;
    /** Article publication date in ISO 8601 format with UTC timezone. */
    published_date: string;
    /** Job ID that found this citation. */
    job_id: string;
    /** The date when the citation was added to the record in ISO 8601 format with UTC timezone. */
    added_on: string;
}
