// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface MonitorListItemDto {
    /** Monitor identifier. */
    monitor_id: string;
    /** Job identifier used as a reference for this monitor. */
    reference_job_id: string;
    /** Natural language query from the reference job. */
    reference_job_query: string;
    /** Whether the monitor is currently active. */
    enabled: boolean;
    /** Cron expression for monitor schedule. */
    schedule?: string;
    /** Natural language description of the monitor schedule. */
    schedule_human_readable?: string;
    /** Timezone for schedule execution. */
    timezone?: string;
    /** The date when the monitor was created. */
    created_at?: string;
    /** Webhook configuration for this monitor (if set). */
    webhook?: CatchAllApi.WebhookDto;
}
