// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * Citation with monitor-specific metadata. Used in monitor results and webhook payloads.
 * Extends base citation with tracking information for job_id and timestamps.
 */
export interface MonitorCitation extends CatchAllApi.Citation {
    /** Unique identifier of the document in the search index. */
    id: string;
    /** Job ID that found this citation. */
    job_id: string;
    /** The date when the citation was added to the record in ISO 8601 format with UTC timezone. */
    added_on: string;
}
