// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface MonitorStatusHistoryResponseDto {
    /** True if the request succeeded; false otherwise. */
    success: boolean;
    /** Optional message. `null` on success. */
    message?: (string | null) | undefined;
    /** Monitor identifier. `null` on failure. */
    monitor_id: string | null;
    /** Total number of status entries in the history. */
    total_statuses: number | null;
    /** Full status history, ordered newest to oldest. */
    statuses: CatchAllApi.MonitorStatusEntry[] | null;
}
