// This file was auto-generated by Fern from our API Definition.

/**
 * Controls which resources are returned based on ownership.
 *
 * - `all`: Returns resources owned by the user and resources shared
 *   with them (default, backward compatible).
 * - `own`: Returns only resources created by the authenticated user.
 * - `shared`: Returns only resources shared with the user by others.
 */
export const OwnershipFilter = {
    All: "all",
    Own: "own",
    Shared: "shared",
} as const;
export type OwnershipFilter = (typeof OwnershipFilter)[keyof typeof OwnershipFilter];
