// This file was auto-generated by Fern from our API Definition.

/**
 * Resource type for project association.
 *
 * Unlike the other types, a `webhook` may be attached to several projects at
 * once, and deleting a project never deletes its webhooks.
 */
export const ProjectResourceType = {
    Job: "job",
    Monitor: "monitor",
    Dataset: "dataset",
    MonitorGroup: "monitor_group",
    Webhook: "webhook",
} as const;
export type ProjectResourceType = (typeof ProjectResourceType)[keyof typeof ProjectResourceType];
