// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * A resource assigned to a project.
 */
export interface ProjectResourceDto {
    resource_type: CatchAllApi.ProjectResourceType;
    /** Resource identifier. */
    resource_id: string;
    /**
     * Resource display name. For jobs, this is the original query
     * string. For monitors, datasets, and webhooks, this is the resource name.
     */
    name?: string | undefined;
    /** Resource creation timestamp. */
    created_at?: string | undefined;
    /** Additional resource-specific metadata. */
    metadata?: Record<string, unknown> | undefined;
}
