// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ProjectOverviewResponseDto {
    /** Project identifier. */
    project_id: string;
    /** Resource counts grouped by type. */
    overview: ProjectOverviewResponseDto.Overview;
}

export namespace ProjectOverviewResponseDto {
    /**
     * Resource counts grouped by type.
     */
    export interface Overview {
        jobs: CatchAllApi.ProjectOverviewCountsDto;
        monitors: CatchAllApi.ProjectOverviewCountsDto;
        datasets: CatchAllApi.ProjectOverviewCountsDto;
        monitor_groups: CatchAllApi.ProjectOverviewCountsDto;
        webhooks: CatchAllApi.ProjectOverviewCountsDto;
    }
}
