// This file was auto-generated by Fern from our API Definition.

export interface ProjectResponseDto {
    /** True if the operation succeeded; false otherwise. */
    success: boolean;
    /** Human-readable result message. */
    message: string;
    /** Project identifier. */
    project_id: string;
    /** Project name. */
    name: string;
    /** Project description. */
    description?: (string | null) | undefined;
    /** Number of resources assigned to this project. */
    resources_count?: number | undefined;
    /** Project creation timestamp. */
    created_at?: string | undefined;
    /** Timestamp of the last update. */
    updated_at?: string | undefined;
}
