// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ProjectResourceListResponseDto {
    /** Total number of resources assigned to the project. */
    total: number;
    /** Current page number. */
    page: number;
    /** Number of resources per page. */
    page_size: number;
    /** Total number of pages. */
    total_pages: number;
    /** Resources on this page. */
    resources: CatchAllApi.ProjectResourceDto[];
}
