// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ProjectListResponseDto {
    /** Total number of projects matching the filter criteria. */
    total: number;
    /** Current page number. */
    page: number;
    /** Number of projects per page. */
    page_size: number;
    /** Total number of pages. */
    total_pages: number;
    /** Projects on this page. */
    projects: CatchAllApi.ProjectSummaryDto[];
}
