// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface PullJobResponseDto {
    /** Job identifier. */
    job_id: string;
    /** Original plain text query. */
    query?: string | undefined;
    /** Context provided with the query. */
    context?: string | undefined;
    /** List of validation criteria applied to filter results. */
    validators?: string[] | undefined;
    /**
     * List of extracted field names generated by the enrichment process. These field names appear in the `enrichment` object of each record.
     *
     * **Note:** The `enrichment_confidence` field always appears in this list. The system adds it to every record regardless of the enrichments generated or defined.
     */
    enrichments?: string[] | undefined;
    /** Job status. */
    status?: string | undefined;
    /** Error message if the job failed. Null for successful jobs. */
    error?: (string | null) | undefined;
    /** Record limit for this job. Reflects the value specified at submit time, or the plan default if no limit was provided. */
    limit?: number | undefined;
    /** Total time taken to process the job. */
    duration?: string | undefined;
    /** Total number of distinct event clusters identified. Compare with `progress_validated` to estimate how many candidates remain unprocessed for job continuation. */
    candidate_records?: number | undefined;
    /** Number of validated records extracted. */
    valid_records?: number | undefined;
    /**
     * Number of candidate clusters that have been validated during processing.
     *
     * The system process data in batches. This field tracks how many `candidate_records` have been checked against validation criteria so far.
     */
    progress_validated?: (number | null) | undefined;
    date_range?: PullJobResponseDto.DateRange | undefined;
    /** The current page number. */
    page?: number | undefined;
    /** The number of records per page. */
    page_size?: number | undefined;
    /** The total number of pages available. */
    total_pages?: number | undefined;
    /** Array of extracted records with structured data and citations. */
    all_records?: CatchAllApi.Record_[] | undefined;
}

export namespace PullJobResponseDto {
    export interface DateRange {
        start_date?: string | undefined;
        end_date?: string | undefined;
    }
}
