// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface PullJobResponseDto {
    /** Job identifier. */
    job_id: string;
    /** Original natural language query. */
    query?: string;
    /** Context provided with the query. */
    context?: string;
    /** List of validation criteria applied to filter results. */
    validators?: string[];
    /**
     * List of extracted field names generated by the enrichment process.
     * These field names appear in the `enrichment` object of each record.
     */
    enrichments?: string[];
    /** Job status. */
    status: string;
    /** Total time taken to process the job. */
    duration?: string;
    /** Number of distinct event clusters identified before validation. */
    candidate_records?: number;
    /** Number of validated records extracted. */
    valid_records?: number;
    /**
     * Number of candidate clusters that have been validated during processing.
     *
     * The system process data in batches. This field tracks how many candidates have been checked against validation criteria so far.
     */
    progress_validated?: number;
    date_range?: PullJobResponseDto.DateRange;
    /** The current page number. */
    page?: number;
    /** The total number of pages available. */
    total_pages?: number;
    /** The number of records per page. */
    page_size?: number;
    /** Array of extracted records with structured data and citations. */
    all_records?: CatchAllApi.Record_[];
}

export namespace PullJobResponseDto {
    export interface DateRange {
        start_date?: string;
        end_date?: string;
    }
}
