// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface PullJobResponseDto {
    /** Job identifier. */
    job_id: string;
    /** Original natural language query. */
    query?: string | undefined;
    /** Context provided with the query. */
    context?: string | undefined;
    /** List of validation criteria applied to filter results. */
    validators?: string[] | undefined;
    /**
     * List of extracted field names generated by the enrichment process.
     * These field names appear in the `enrichment` object of each record.
     */
    enrichments?: string[] | undefined;
    /** Job status. */
    status: string;
    /** Total time taken to process the job. */
    duration?: string | undefined;
    /** Number of distinct event clusters identified before validation. */
    candidate_records?: number | undefined;
    /** Number of validated records extracted. */
    valid_records?: number | undefined;
    /**
     * Number of candidate clusters that have been validated during processing.
     *
     * The system process data in batches. This field tracks how many candidates have been checked against validation criteria so far.
     */
    progress_validated?: number | undefined;
    date_range?: PullJobResponseDto.DateRange | undefined;
    /** The current page number. */
    page?: number | undefined;
    /** The total number of pages available. */
    total_pages?: number | undefined;
    /** The number of records per page. */
    page_size?: number | undefined;
    /** Array of extracted records with structured data and citations. */
    all_records?: CatchAllApi.Record_[] | undefined;
}

export namespace PullJobResponseDto {
    export interface DateRange {
        start_date?: string | undefined;
        end_date?: string | undefined;
    }
}
