// This file was auto-generated by Fern from our API Definition.

/**
 * Natural language question describing what to find.
 *
 * The system analyzes your input to generate search queries, validators, and extractors. More specific queries produce more focused results.
 */
export type Query = string;
