// This file was auto-generated by Fern from our API Definition.

/**
 * Quality level assigned to a query by the validation endpoint.
 *
 * - `good`: Query is well-formed and likely to produce relevant results.
 * - `needs_work`: Query has issues that may reduce result quality. Review `suggestions` for improvements.
 * - `critical`: Query is unlikely to produce useful results as written. Address all `issues` before submitting.
 */
export const QueryStatus = {
    Good: "good",
    NeedsWork: "needs_work",
    Critical: "critical",
} as const;
export type QueryStatus = (typeof QueryStatus)[keyof typeof QueryStatus];
