// This file was auto-generated by Fern from our API Definition.

export interface ReferenceJob {
    /** Plain text query from the reference job. */
    query?: string | undefined;
    /** Context provided with the reference job query. */
    context?: string | undefined;
}
