// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ReferenceJob {
    /** Plain text query from the reference job. */
    query?: string | undefined;
    /** Context provided with the reference job query. */
    context?: string | undefined;
    /**
     * Source groups attached to the reference job, each with `slug`, `name`, and
     * `description`. `null` when the reference job was not scoped to any source group.
     */
    source_groups?: (CatchAllApi.SourceGroupRef[] | null) | undefined;
}
