// This file was auto-generated by Fern from our API Definition.

export interface RemoveResourceResponseDto {
    /** True if the operation succeeded; false otherwise. */
    success: boolean;
    /** Human-readable result message. */
    message: string;
}
