// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ResourceItemDto {
    resource_type: CatchAllApi.ProjectResourceType;
    /** ID of the resource to add. */
    resource_id: string;
}
