// This file was auto-generated by Fern from our API Definition.

/**
 * Template string to guide record summary formatting. Use placeholder syntax with brackets to indicate desired fields: [COMPANY], [REVENUE], [TARGET], [AMOUNT], etc.
 *
 * When provided, the system generates a `schema_based_summary` field for each record following this template.
 */
export type Schema = string;
