// This file was auto-generated by Fern from our API Definition.

/**
 * Present on resources shared with the authenticated user by another
 * organization member. Omitted entirely on resources the user owns.
 */
export interface SharingInfo {
    /** When the resource was shared. */
    shared_at: string;
    /** Permission level granted to the recipient. */
    permission: SharingInfo.Permission;
    /**
     * Display name of the user who shared the resource (first + last
     * name). Falls back to email address, then user ID.
     */
    shared_by: string;
}

export namespace SharingInfo {
    /** Permission level granted to the recipient. */
    export const Permission = {
        View: "view",
        Edit: "edit",
        Manage: "manage",
    } as const;
    export type Permission = (typeof Permission)[keyof typeof Permission];
}
