// This file was auto-generated by Fern from our API Definition.

/**
 * Details about a CSV row that was skipped during processing.
 */
export interface SkippedRow {
    /**
     * 1-based row number in the CSV file (including the header row).
     *
     * A value of `3` means the third line of the file (second data row).
     */
    row: number;
    /** Human-readable explanation of why the row was skipped. */
    reason: string;
}
