// This file was auto-generated by Fern from our API Definition.

/**
 * Sort direction for list results.
 *
 * - `asc`: ascending (oldest or smallest first)
 * - `desc`: descending (newest or largest first)
 */
export const SortOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];
