// This file was auto-generated by Fern from our API Definition.

/**
 * A source group attached to a job, returned with its slug, name, and description.
 *
 * Source groups are curated domain allowlists maintained by NewsCatcher. Attach one
 * to a job with `source_groups` on job creation to scope fetching to its domains.
 */
export interface SourceGroupRef {
    /**
     * Stable identifier for the source group. This is the value you pass in
     * `source_groups` when creating a job.
     */
    slug: string;
    /** Human-readable name of the source group. */
    name: string;
    /** What the group covers, when set. */
    description?: (string | null) | undefined;
}
