// This file was auto-generated by Fern from our API Definition.

/**
 * Start of date range for article search (ISO 8601 format with UTC timezone).
 *
 * Must be within plan's allowed lookback period. Default is 5 days before current date if not specified.
 */
export type StartDate = string;
