// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface StatusResponseDto {
    /** Job identifier. */
    job_id: string;
    /** Internal job processing status. Use the `steps` array for reliable status tracking. */
    status?: string;
    /** Detailed progress tracking for each processing stage. Steps progress sequentially from order 1 (submitted) through 5 (enriching), ending at order 6 (completed) or 7 (failed). */
    steps: CatchAllApi.JobStep[];
}
