// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * Actionable recommendation for improving a query.
 */
export interface Suggestion {
    /** The issue this suggestion addresses. */
    issue: CatchAllApi.IssueType;
    /** Specific guidance for improving the query. */
    message: string;
    /** Revised query demonstrating the suggested improvement. */
    example?: string | undefined;
}
