// This file was auto-generated by Fern from our API Definition.

export interface TestWebhookResponseDto {
    /** True if the test delivery received a 2xx response; false otherwise. */
    success: boolean;
    /** Human-readable result message. */
    message: string;
    /** HTTP status code returned by the webhook endpoint. */
    http_status_code?: number | undefined;
    /** Response body returned by the webhook endpoint. Type varies by target. */
    response_body?: unknown | undefined;
}
