// This file was auto-generated by Fern from our API Definition.

export interface UpdateMonitorResponseDto {
    /** Monitor identifier. */
    monitor_id: string;
    /** Confirmation message. */
    status: string;
}
