// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface UploadCsvToDatasetResponse {
    /** ID of the dataset that was updated. */
    dataset_id: string;
    /** Number of new entities created from the CSV. */
    entities_created: number;
    validation_report: CatchAllApi.ValidationReport;
}
