// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * Query quality assessment returned by the validate endpoint.
 */
export interface ValidateQueryResponseDto {
    /** Overall quality level of the query. */
    status: CatchAllApi.QueryStatus;
    /** Short headline summarising the assessment. */
    title: string;
    /** Plain-language explanation of the assessment result. */
    description?: string | undefined;
    /** Issues identified in the query. Empty when `status` is `good`. */
    issues?: CatchAllApi.IssueType[] | undefined;
    /** Actionable recommendations for each identified issue. Empty when `status` is `good`. Each suggestion corresponds to one entry in `issues`. */
    suggestions?: CatchAllApi.Suggestion[] | undefined;
    /** Confidence score for this assessment. */
    confidence: number;
}
