// This file was auto-generated by Fern from our API Definition.

/**
 * Schema for a single validator that filters article clusters.
 *
 * Validators are applied during the enriching stage to determine which clusters are relevant.
 */
export interface ValidatorSchema {
    /** Validator field name (snake_case recommended). */
    name: string;
    /** What this validator checks for in the article. */
    description: string;
    /** Validator type (currently only boolean supported). */
    type?: "boolean";
}
