// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface ValidationErrorResponse {
    detail?: CatchAllApi.ValidationErrorDetail[];
}
