// This file was auto-generated by Fern from our API Definition.

export interface ValidationErrorDetail {
    /** Location of the validation error */
    loc?: ValidationErrorDetail.Loc.Item[];
    /** Error message */
    msg?: string;
    /** Error type */
    type?: string;
}

export namespace ValidationErrorDetail {
    export type Loc = Loc.Item[];

    export namespace Loc {
        export type Item = string | number;
    }
}
