// This file was auto-generated by Fern from our API Definition.

export interface WebhookResourceMappingResponseDto {
    /** Mapping identifier. */
    id: string;
    /** Webhook identifier. */
    webhook_id: string;
    /** Type of the assigned resource. */
    resource_type: string;
    /** Identifier of the assigned resource. */
    resource_id: string;
    /** Timestamp when the resource was assigned in ISO 8601 format with UTC timezone. */
    assigned_at?: string | undefined;
}
