// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

/**
 * **First execution:** The initial webhook after monitor creation includes all records from the reference job, providing immediate access to collected data.
 *
 * **Subsequent executions:** Only new records (after deduplication) are included.
 */
export interface WebhookPayload {
    /** Monitor identifier. */
    monitor_id?: string;
    /** Reference job used as template for this monitor. */
    reference_job_id?: string;
    /** Job ID of the most recent execution. */
    latest_job_id?: string;
    /** Number of new records from latest job (after deduplication). */
    records_count?: number;
    /** Total number of jobs executed by this monitor. */
    jobs_processed?: number;
    /** The date when the webhook was triggered in ISO 8601 format with UTC timezone. */
    updated_at?: string;
    /** Cron expression defining the monitor schedule. */
    cron_expression?: string;
    /** Timezone for schedule execution. */
    timezone?: string;
    /** Array of new records from the latest job execution (includes monitor-specific fields like added_on, updated_on). */
    records?: CatchAllApi.MonitorRecord[];
}
