// This file was auto-generated by Fern from our API Definition.

/**
 * Resource types a delivery history record can be attributed to.
 *
 * A superset of `MappableResourceType`. Real deliveries are always tied to an
 * assignable resource (`job`, `monitor`, or `monitor_group`), but a manual test
 * delivery triggered through [`POST /catchAll/webhooks/{webhook_id}/test`](https://www.newscatcherapi.com/docs/web-search-api/api-reference/webhooks/test-webhook)
 * is not tied to any real resource, so it is recorded against the synthetic
 * `test` type. `test` is only ever returned in delivery history — it is never
 * accepted when assigning a webhook to a resource.
 */
export const WebhookHistoryResourceType = {
    Job: "job",
    Monitor: "monitor",
    MonitorGroup: "monitor_group",
    Test: "test",
} as const;
export type WebhookHistoryResourceType = (typeof WebhookHistoryResourceType)[keyof typeof WebhookHistoryResourceType];
