// This file was auto-generated by Fern from our API Definition.

export interface WebhookDto {
    /** Webhook endpoint URL. */
    url: string;
    /** HTTP method to use. */
    method?: WebhookDto.Method | undefined;
    /** HTTP headers to include in request. */
    headers?: Record<string, string> | undefined;
    /** Query string parameters. */
    params?: Record<string, unknown> | undefined;
    /** Basic auth credentials [username, password]. */
    auth?: string[] | undefined;
}

export namespace WebhookDto {
    /** HTTP method to use. */
    export const Method = {
        Post: "POST",
        Put: "PUT",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
