// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export type WebhookResponseDtoAuth =
    | CatchAllApi.WebhookResponseDtoAuth.Bearer
    | CatchAllApi.WebhookResponseDtoAuth.ApiKey
    | CatchAllApi.WebhookResponseDtoAuth.Basic;

export namespace WebhookResponseDtoAuth {
    export interface Bearer extends CatchAllApi.BearerAuthResponseDto {
        type: "bearer";
    }

    export interface ApiKey extends CatchAllApi.ApiKeyAuthResponseDto {
        type: "api_key";
    }

    export interface Basic extends CatchAllApi.BasicAuthResponseDto {
        type: "basic";
    }
}
