// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../index.js";

export interface WebhookResponseDto {
    /** Webhook identifier. */
    id: string;
    /** Human-readable label for this webhook. */
    name: string;
    /** Destination URL that receives the payload. */
    url: string;
    type: CatchAllApi.WebhookType;
    delivery_mode: CatchAllApi.DeliveryMode;
    method: CatchAllApi.HttpMethod;
    /** Custom HTTP headers forwarded with each delivery. */
    headers?: Record<string, string> | undefined;
    /** Query parameters appended to the webhook URL. */
    params?: Record<string, string> | undefined;
    /** Custom payload transformation configuration. Used only when `type` is `custom`. */
    formatter_config?: (Record<string, unknown> | null) | undefined;
    /** True if the webhook is active; false otherwise. */
    is_active: boolean;
    /** Organization that owns this webhook. */
    organization_id?: string | undefined;
    /** ID of the user who created this webhook. */
    created_by_user_id?: string | undefined;
    /** Webhook creation timestamp in ISO 8601 format with UTC timezone. */
    created_at?: string | undefined;
    /** Timestamp of the last update in ISO 8601 format with UTC timezone. */
    updated_at?: string | undefined;
}
