// This file was auto-generated by Fern from our API Definition.

/**
 * Webhook target type.
 *
 * - `generic`: Sends the raw result payload to any HTTPS endpoint.
 * - `slack`: Sends a formatted Slack Block Kit message. URL must start with `https://hooks.slack.com/`.
 * - `teams`: Sends a formatted Microsoft Teams Adaptive Card. URL hostname must match `*webhook.office.com` or `*.webhook.office365.com`.
 * - `custom`: Sends a transformed payload using the configuration in `formatter_config`. Requires `formatter_config` to be set.
 *
 * When `type` is omitted, it is auto-detected from the URL.
 */
export const WebhookType = {
    Generic: "generic",
    Slack: "slack",
    Teams: "teams",
    Custom: "custom",
} as const;
export type WebhookType = (typeof WebhookType)[keyof typeof WebhookType];
