// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as CatchAllApi from "../../../index.js";

export declare namespace MonitorsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations to create, operate and retrieve monitor results.
 */
export class MonitorsClient {
    protected readonly _options: MonitorsClient.Options;

    constructor(options: MonitorsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Create a monitor that runs jobs based on a reference job with a specified schedule.
     *
     * **Warning**: Schedule validation is limited. Invalid schedules may be parsed incorrectly.
     * Always test schedules before production use.
     *
     * @param {CatchAllApi.CreateMonitorRequestDto} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CatchAllApi.UnprocessableEntityError}
     *
     * @example
     *     await client.monitors.createMonitor({
     *         reference_job_id: "reference_job_id",
     *         schedule: "every day at 12 PM UTC"
     *     })
     */
    public createMonitor(
        request: CatchAllApi.CreateMonitorRequestDto,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.CreateMonitorResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__createMonitor(request, requestOptions));
    }

    private async __createMonitor(
        request: CatchAllApi.CreateMonitorRequestDto,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.CreateMonitorResponseDto>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                "catchAll/monitors/create",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.CreateMonitorResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new CatchAllApi.UnprocessableEntityError(
                        _response.error.body as CatchAllApi.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CatchAllApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CatchAllApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CatchAllApiTimeoutError(
                    "Timeout exceeded when calling POST /catchAll/monitors/create.",
                );
            case "unknown":
                throw new errors.CatchAllApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns all jobs associated with a monitor, sorted by start_date.
     * Each job includes job_id, start_date, and end_date.
     *
     * @param {CatchAllApi.ListMonitorJobsRequest} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CatchAllApi.NotFoundError}
     * @throws {@link CatchAllApi.UnprocessableEntityError}
     *
     * @example
     *     await client.monitors.listMonitorJobs({
     *         monitor_id: "monitor_id"
     *     })
     */
    public listMonitorJobs(
        request: CatchAllApi.ListMonitorJobsRequest,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.ListMonitorJobsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listMonitorJobs(request, requestOptions));
    }

    private async __listMonitorJobs(
        request: CatchAllApi.ListMonitorJobsRequest,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.ListMonitorJobsResponse>> {
        const { monitor_id: monitorId, sort } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (sort != null) {
            _queryParams.sort = sort;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                `catchAll/monitors/${core.url.encodePathParam(monitorId)}/jobs`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.ListMonitorJobsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CatchAllApi.NotFoundError(
                        _response.error.body as CatchAllApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new CatchAllApi.UnprocessableEntityError(
                        _response.error.body as CatchAllApi.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CatchAllApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CatchAllApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CatchAllApiTimeoutError(
                    "Timeout exceeded when calling GET /catchAll/monitors/{monitor_id}/jobs.",
                );
            case "unknown":
                throw new errors.CatchAllApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve aggregated results from all jobs executed by this monitor.
     * Includes monitor configuration, execution history, and all records collected.
     *
     * @param {CatchAllApi.PullMonitorResultsRequest} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CatchAllApi.NotFoundError}
     * @throws {@link CatchAllApi.UnprocessableEntityError}
     *
     * @example
     *     await client.monitors.pullMonitorResults({
     *         monitor_id: "monitor_id"
     *     })
     */
    public pullMonitorResults(
        request: CatchAllApi.PullMonitorResultsRequest,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.PullMonitorResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__pullMonitorResults(request, requestOptions));
    }

    private async __pullMonitorResults(
        request: CatchAllApi.PullMonitorResultsRequest,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.PullMonitorResponseDto>> {
        const { monitor_id: monitorId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                `catchAll/monitors/pull/${core.url.encodePathParam(monitorId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.PullMonitorResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new CatchAllApi.NotFoundError(
                        _response.error.body as CatchAllApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new CatchAllApi.UnprocessableEntityError(
                        _response.error.body as CatchAllApi.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CatchAllApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CatchAllApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CatchAllApiTimeoutError(
                    "Timeout exceeded when calling GET /catchAll/monitors/pull/{monitor_id}.",
                );
            case "unknown":
                throw new errors.CatchAllApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Disables a monitor to stop executing scheduled jobs.
     * Validates that the provided API key is associated with the monitor.
     *
     * @param {CatchAllApi.DisableMonitorRequest} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CatchAllApi.ForbiddenError}
     * @throws {@link CatchAllApi.NotFoundError}
     * @throws {@link CatchAllApi.UnprocessableEntityError}
     *
     * @example
     *     await client.monitors.disableMonitor({
     *         monitor_id: "monitor_id"
     *     })
     */
    public disableMonitor(
        request: CatchAllApi.DisableMonitorRequest,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.DisableMonitorResponse> {
        return core.HttpResponsePromise.fromPromise(this.__disableMonitor(request, requestOptions));
    }

    private async __disableMonitor(
        request: CatchAllApi.DisableMonitorRequest,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.DisableMonitorResponse>> {
        const { monitor_id: monitorId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                `catchAll/monitors/${core.url.encodePathParam(monitorId)}/disable`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.DisableMonitorResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new CatchAllApi.ForbiddenError(
                        _response.error.body as CatchAllApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new CatchAllApi.NotFoundError(
                        _response.error.body as CatchAllApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new CatchAllApi.UnprocessableEntityError(
                        _response.error.body as CatchAllApi.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CatchAllApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CatchAllApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CatchAllApiTimeoutError(
                    "Timeout exceeded when calling POST /catchAll/monitors/{monitor_id}/disable.",
                );
            case "unknown":
                throw new errors.CatchAllApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Enables a monitor to resume executing scheduled jobs.
     * Validates that the provided API key is associated with the monitor.
     *
     * @param {CatchAllApi.EnableMonitorRequest} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CatchAllApi.ForbiddenError}
     * @throws {@link CatchAllApi.NotFoundError}
     * @throws {@link CatchAllApi.UnprocessableEntityError}
     *
     * @example
     *     await client.monitors.enableMonitor({
     *         monitor_id: "monitor_id"
     *     })
     */
    public enableMonitor(
        request: CatchAllApi.EnableMonitorRequest,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.EnableMonitorResponse> {
        return core.HttpResponsePromise.fromPromise(this.__enableMonitor(request, requestOptions));
    }

    private async __enableMonitor(
        request: CatchAllApi.EnableMonitorRequest,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.EnableMonitorResponse>> {
        const { monitor_id: monitorId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                `catchAll/monitors/${core.url.encodePathParam(monitorId)}/enable`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.EnableMonitorResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new CatchAllApi.ForbiddenError(
                        _response.error.body as CatchAllApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new CatchAllApi.NotFoundError(
                        _response.error.body as CatchAllApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new CatchAllApi.UnprocessableEntityError(
                        _response.error.body as CatchAllApi.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CatchAllApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CatchAllApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CatchAllApiTimeoutError(
                    "Timeout exceeded when calling POST /catchAll/monitors/{monitor_id}/enable.",
                );
            case "unknown":
                throw new errors.CatchAllApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns all monitors created by the authenticated user.
     *
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CatchAllApi.ForbiddenError}
     * @throws {@link CatchAllApi.UnprocessableEntityError}
     *
     * @example
     *     await client.monitors.listMonitors()
     */
    public listMonitors(
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.ListMonitorsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__listMonitors(requestOptions));
    }

    private async __listMonitors(
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.ListMonitorsResponseDto>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                "catchAll/monitors",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.ListMonitorsResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new CatchAllApi.ForbiddenError(
                        _response.error.body as CatchAllApi.Error_,
                        _response.rawResponse,
                    );
                case 422:
                    throw new CatchAllApi.UnprocessableEntityError(
                        _response.error.body as CatchAllApi.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CatchAllApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.CatchAllApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.CatchAllApiTimeoutError("Timeout exceeded when calling GET /catchAll/monitors.");
            case "unknown":
                throw new errors.CatchAllApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
