// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import type * as CatchAllApi from "../../../index.js";

export declare namespace MetaClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations to check API health and version.
 */
export class MetaClient {
    protected readonly _options: NormalizedClientOptions<MetaClient.Options>;

    constructor(options: MetaClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Check API availability.
     *
     * @param {MetaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.meta.healthCheck()
     */
    public healthCheck(
        requestOptions?: MetaClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.HealthCheckResponse> {
        return core.HttpResponsePromise.fromPromise(this.__healthCheck(requestOptions));
    }

    private async __healthCheck(
        requestOptions?: MetaClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.HealthCheckResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                "health",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.HealthCheckResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CatchAllApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/health");
    }

    /**
     * Returns current API version.
     *
     * @param {MetaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.meta.getVersion()
     */
    public getVersion(
        requestOptions?: MetaClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.GetVersionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getVersion(requestOptions));
    }

    private async __getVersion(
        requestOptions?: MetaClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.GetVersionResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                "version",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.GetVersionResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CatchAllApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/version");
    }
}
