// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as CatchAllApi from "../../../index.js";

export declare namespace MetaClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations to check API health and version.
 */
export class MetaClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MetaClient.Options>;

    constructor(options: MetaClient.Options = {}) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Check API availability.
     *
     * @param {MetaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.meta.healthCheck()
     */
    public healthCheck(
        requestOptions?: MetaClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.HealthCheckResponse> {
        return core.HttpResponsePromise.fromPromise(this.__healthCheck(requestOptions));
    }

    private async __healthCheck(
        requestOptions?: MetaClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.HealthCheckResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                "health",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.HealthCheckResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CatchAllApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/health");
    }

    /**
     * Returns current API version.
     *
     * @param {MetaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.meta.getVersion()
     */
    public getVersion(
        requestOptions?: MetaClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.GetVersionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getVersion(requestOptions));
    }

    private async __getVersion(
        requestOptions?: MetaClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.GetVersionResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                "version",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.GetVersionResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.CatchAllApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/version");
    }

    /**
     * Returns plan features and current usage for the authenticated organization.
     *
     * @param {MetaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link CatchAllApi.ForbiddenError}
     *
     * @example
     *     await client.meta.getPlanLimits()
     */
    public getPlanLimits(
        requestOptions?: MetaClient.RequestOptions,
    ): core.HttpResponsePromise<CatchAllApi.GetPlanLimitsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getPlanLimits(requestOptions));
    }

    private async __getPlanLimits(
        requestOptions?: MetaClient.RequestOptions,
    ): Promise<core.WithRawResponse<CatchAllApi.GetPlanLimitsResponseDto>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.CatchAllApiEnvironment.Default,
                "catchAll/user/limits",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as CatchAllApi.GetPlanLimitsResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new CatchAllApi.ForbiddenError(
                        _response.error.body as CatchAllApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.CatchAllApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/catchAll/user/limits");
    }
}
