// This file was auto-generated by Fern from our API Definition.

export interface DisableMonitorResponse {
    /** Whether the operation succeeded. */
    success: boolean;
    /** Human-readable success message. */
    message: string;
    /** ID of the disabled monitor. */
    monitor_id: string;
}
