// This file was auto-generated by Fern from our API Definition.

export interface EnableMonitorResponse {
    /** True if the operation succeeded; false otherwise. */
    success: boolean;
    /** Human-readable success message. */
    message: string;
    /** ID of the enabled monitor. */
    monitor_id: string;
}
