// This file was auto-generated by Fern from our API Definition.

import type * as CatchAllApi from "../../../index.js";

export interface ListMonitorJobsResponse {
    /** Monitor identifier. */
    monitor_id: string;
    /** Sort order applied to results. */
    sort_order: ListMonitorJobsResponse.SortOrder;
    /** Total number of jobs for this monitor. */
    total_jobs: number;
    /** Array of job executions for this monitor. */
    jobs: CatchAllApi.MonitorJobItem[];
}

export namespace ListMonitorJobsResponse {
    /** Sort order applied to results. */
    export const SortOrder = {
        Asc: "asc",
        Desc: "desc",
    } as const;
    export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];
}
