// This file was auto-generated by Fern from our API Definition.

export const GetUserJobsRequestMode = {
    Lite: "lite",
    Base: "base",
} as const;
export type GetUserJobsRequestMode = (typeof GetUserJobsRequestMode)[keyof typeof GetUserJobsRequestMode];
