// This file was auto-generated by Fern from our API Definition.

import * as CatchAllApi from "../../src/api/index";
import { CatchAllApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EntitiesClient", () => {
    test("listEntities (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            entities: [
                {
                    id: "854198fa-f702-49db-a381-0427fa87f173",
                    entity_type: "company",
                    organization_id: "e5d9e9b0-e415-4941-8ef0-916c5ee56207",
                    name: "NewsCatcher",
                    description: "AI-powered news data provider",
                    additional_attributes: {
                        company_attributes: {
                            domain: "newscatcherapi.com",
                            description: "Provider of news and web search APIs for developers",
                            key_persons: ["Artem Bugara", "Maksym Sugonyaka"],
                            alternative_names: ["NC", "NewsCatcher API"],
                        },
                    },
                    status: "pending",
                    created_by_user_id: "870e258e-12ec-4a47-8656-e7a43b0265b3",
                    created_at: "2026-04-08T15:21:17Z",
                    updated_at: "2026-04-08T15:21:18Z",
                },
            ],
            total: 17,
            page: 1,
            page_size: 100,
        };

        server.mockEndpoint().get("/catchAll/entities").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.entities.listEntities({
            search: "NewsCatcher",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listEntities (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/catchAll/entities").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.entities.listEntities();
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("createEntity (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "NewsCatcher",
            entity_type: "company",
            description: "AI-powered news data provider",
            additional_attributes: {
                company_attributes: {
                    domain: "newscatcherapi.com",
                    key_persons: ["Artem Bugara", "Maksym Sugonyaka"],
                    alternative_names: ["NC", "NewsCatcher API"],
                },
            },
        };
        const rawResponseBody = { id: "854198fa-f702-49db-a381-0427fa87f173", status: "pending" };

        server
            .mockEndpoint()
            .post("/catchAll/entities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.createEntity({
            name: "NewsCatcher",
            entity_type: "company",
            description: "AI-powered news data provider",
            additional_attributes: {
                company_attributes: {
                    domain: "newscatcherapi.com",
                    key_persons: ["Artem Bugara", "Maksym Sugonyaka"],
                    alternative_names: ["NC", "NewsCatcher API"],
                },
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createEntity (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/catchAll/entities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.createEntity({
                name: "x",
            });
        }).rejects.toThrow(CatchAllApi.BadRequestError);
    });

    test("createEntity (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/entities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.createEntity({
                name: "x",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("createEntitiesBatch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            entities: [
                {
                    name: "OpenAI",
                    entity_type: "company",
                    description: "Artificial intelligence research company",
                    additional_attributes: {
                        company_attributes: {
                            domain: "openai.com",
                            key_persons: ["Sam Altman"],
                            alternative_names: ["Open AI"],
                        },
                    },
                },
                {
                    name: "Stripe",
                    entity_type: "company",
                    description: "Online payment processing platform",
                    additional_attributes: {
                        company_attributes: {
                            domain: "stripe.com",
                            key_persons: ["Patrick Collison", "John Collison"],
                        },
                    },
                },
            ],
        };
        const rawResponseBody = {
            entities: [
                { id: "88430468-d784-485d-84d5-6964a29ccd1e", status: "pending" },
                { id: "ad4908fe-6db5-4237-a137-68dd8fc9fedc", status: "pending" },
            ],
            count: 2,
        };

        server
            .mockEndpoint()
            .post("/catchAll/entities/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.createEntitiesBatch({
            entities: [
                {
                    name: "OpenAI",
                    entity_type: "company",
                    description: "Artificial intelligence research company",
                    additional_attributes: {
                        company_attributes: {
                            domain: "openai.com",
                            key_persons: ["Sam Altman"],
                            alternative_names: ["Open AI"],
                        },
                    },
                },
                {
                    name: "Stripe",
                    entity_type: "company",
                    description: "Online payment processing platform",
                    additional_attributes: {
                        company_attributes: {
                            domain: "stripe.com",
                            key_persons: ["Patrick Collison", "John Collison"],
                        },
                    },
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createEntitiesBatch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { entities: [{ name: "x" }, { name: "x" }] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/catchAll/entities/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.createEntitiesBatch({
                entities: [
                    {
                        name: "x",
                    },
                    {
                        name: "x",
                    },
                ],
            });
        }).rejects.toThrow(CatchAllApi.BadRequestError);
    });

    test("createEntitiesBatch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { entities: [{ name: "x" }, { name: "x" }] };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/entities/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.createEntitiesBatch({
                entities: [
                    {
                        name: "x",
                    },
                    {
                        name: "x",
                    },
                ],
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getEntity (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "854198fa-f702-49db-a381-0427fa87f173",
            entity_type: "company",
            organization_id: "e5d9e9b0-e415-4941-8ef0-916c5ee56207",
            name: "NewsCatcher",
            description: "AI-powered news data provider",
            additional_attributes: {
                company_attributes: {
                    domain: "newscatcherapi.com",
                    description: "Provider of news and web search APIs for developers",
                    key_persons: ["Artem Bugara", "Maksym Sugonyaka"],
                    alternative_names: ["NC", "NewsCatcher API"],
                },
            },
            status: "ready",
            created_by_user_id: "870e258e-12ec-4a47-8656-e7a43b0265b3",
            created_at: "2026-04-08T15:21:17Z",
            updated_at: "2026-04-08T15:21:18Z",
        };

        server
            .mockEndpoint()
            .get("/catchAll/entities/854198fa-f702-49db-a381-0427fa87f173")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.getEntity({
            entity_id: "854198fa-f702-49db-a381-0427fa87f173",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getEntity (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/entities/entity_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.getEntity({
                entity_id: "entity_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getEntity (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/entities/entity_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.getEntity({
                entity_id: "entity_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("deleteEntity (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/catchAll/entities/854198fa-f702-49db-a381-0427fa87f173")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.entities.deleteEntity({
            entity_id: "854198fa-f702-49db-a381-0427fa87f173",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteEntity (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/entities/entity_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.deleteEntity({
                entity_id: "entity_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("deleteEntity (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/entities/entity_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.deleteEntity({
                entity_id: "entity_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("updateEntity (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            description: "Updated description",
            additional_attributes: { company_attributes: { alternative_names: ["NC", "NewsCatcher API", "NCA"] } },
        };
        const rawResponseBody = {
            id: "854198fa-f702-49db-a381-0427fa87f173",
            entity_type: "company",
            organization_id: "e5d9e9b0-e415-4941-8ef0-916c5ee56207",
            name: "NewsCatcher",
            description: "AI-powered news data provider",
            additional_attributes: {
                company_attributes: {
                    domain: "newscatcherapi.com",
                    description: "Provider of news and web search APIs for developers",
                    key_persons: ["Artem Bugara", "Maksym Sugonyaka"],
                    alternative_names: ["NC", "NewsCatcher API"],
                },
            },
            status: "ready",
            created_by_user_id: "870e258e-12ec-4a47-8656-e7a43b0265b3",
            created_at: "2026-04-08T15:21:17Z",
            updated_at: "2026-04-08T15:21:18Z",
        };

        server
            .mockEndpoint()
            .patch("/catchAll/entities/854198fa-f702-49db-a381-0427fa87f173")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.entities.updateEntity({
            entity_id: "854198fa-f702-49db-a381-0427fa87f173",
            description: "Updated description",
            additional_attributes: {
                company_attributes: {
                    alternative_names: ["NC", "NewsCatcher API", "NCA"],
                },
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateEntity (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/catchAll/entities/entity_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.updateEntity({
                entity_id: "entity_id",
            });
        }).rejects.toThrow(CatchAllApi.BadRequestError);
    });

    test("updateEntity (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/entities/entity_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.updateEntity({
                entity_id: "entity_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("updateEntity (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/entities/entity_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.entities.updateEntity({
                entity_id: "entity_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });
});
