// This file was auto-generated by Fern from our API Definition.

import * as CatchAllApi from "../../src/api/index";
import { CatchAllApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("JobsClient", () => {
    test("initialize (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "AI company acquisitions in fintech last week" };
        const rawResponseBody = {
            validators: [
                {
                    name: "is_acquisition_event",
                    description: "true if article describes a merger or acquisition event",
                    type: "boolean",
                },
                {
                    name: "involves_fintech",
                    description: "true if the companies involved are in the fintech sector",
                    type: "boolean",
                },
            ],
            enrichments: [
                { name: "acquiring_company", description: "Extract the acquiring company name", type: "company" },
                { name: "acquired_company", description: "Extract the acquired company name", type: "text" },
                { name: "deal_value", description: "Extract the deal value if mentioned", type: "number" },
                { name: "announcement_date", description: "Extract the announcement date", type: "date" },
            ],
            start_date: "2026-01-29T00:00:00Z",
            end_date: "2026-02-05T00:00:00Z",
            date_modification_message: [
                "start_date must be >= 2025-01-23, your plan limited to lookback 365 days; we modified start_date to 2025-01-23.",
            ],
        };
        server
            .mockEndpoint()
            .post("/catchAll/initialize")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.initialize({
            query: "AI company acquisitions in fintech last week",
        });
        expect(response).toEqual({
            validators: [
                {
                    name: "is_acquisition_event",
                    description: "true if article describes a merger or acquisition event",
                    type: "boolean",
                },
                {
                    name: "involves_fintech",
                    description: "true if the companies involved are in the fintech sector",
                    type: "boolean",
                },
            ],
            enrichments: [
                {
                    name: "acquiring_company",
                    description: "Extract the acquiring company name",
                    type: "company",
                },
                {
                    name: "acquired_company",
                    description: "Extract the acquired company name",
                    type: "text",
                },
                {
                    name: "deal_value",
                    description: "Extract the deal value if mentioned",
                    type: "number",
                },
                {
                    name: "announcement_date",
                    description: "Extract the announcement date",
                    type: "date",
                },
            ],
            start_date: "2026-01-29T00:00:00Z",
            end_date: "2026-02-05T00:00:00Z",
            date_modification_message: [
                "start_date must be >= 2025-01-23, your plan limited to lookback 365 days; we modified start_date to 2025-01-23.",
            ],
        });
    });

    test("initialize (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/initialize")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.initialize({
                query: "query",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("initialize (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/initialize")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.initialize({
                query: "query",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("createJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            query: "AI company acquisitions",
            context: "Focus on deal size and acquiring company details",
            limit: 10,
            start_date: "2026-01-30T00:00:00Z",
            end_date: "2026-02-05T00:00:00Z",
        };
        const rawResponseBody = { job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3" };
        server
            .mockEndpoint()
            .post("/catchAll/submit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.createJob({
            query: "AI company acquisitions",
            context: "Focus on deal size and acquiring company details",
            limit: 10,
            start_date: "2026-01-30T00:00:00Z",
            end_date: "2026-02-05T00:00:00Z",
        });
        expect(response).toEqual({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
        });
    });

    test("createJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/submit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                query: "query",
            });
        }).rejects.toThrow(CatchAllApi.BadRequestError);
    });

    test("createJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/submit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                query: "query",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("createJob (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/submit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                query: "query",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("continueJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3", new_limit: 100 };
        const rawResponseBody = {
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
            previous_limit: 10,
            new_limit: 100,
            status: "accepted",
        };
        server
            .mockEndpoint()
            .post("/catchAll/continue")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.continueJob({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
            new_limit: 100,
        });
        expect(response).toEqual({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
            previous_limit: 10,
            new_limit: 100,
            status: "accepted",
        });
    });

    test("continueJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { job_id: "job_id", new_limit: 1 };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/continue")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.continueJob({
                job_id: "job_id",
                new_limit: 1,
            });
        }).rejects.toThrow(CatchAllApi.BadRequestError);
    });

    test("continueJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { job_id: "job_id", new_limit: 1 };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/continue")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.continueJob({
                job_id: "job_id",
                new_limit: 1,
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("continueJob (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { job_id: "job_id", new_limit: 1 };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/continue")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.continueJob({
                job_id: "job_id",
                new_limit: 1,
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("getJobStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
            status: "analyzing",
            steps: [
                { status: "submitted", order: 1, completed: true },
                { status: "analyzing", order: 2, completed: false },
                { status: "fetching", order: 3, completed: false },
                { status: "clustering", order: 4, completed: false },
                { status: "enriching", order: 5, completed: false },
                { status: "completed", order: 6, completed: false },
                { status: "failed", order: 7, completed: false },
            ],
        };
        server
            .mockEndpoint()
            .get("/catchAll/status/af7a26d6-cf0b-458c-a6ed-4b6318c74da3")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getJobStatus({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
        });
        expect(response).toEqual({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
            status: "analyzing",
            steps: [
                {
                    status: "submitted",
                    order: 1,
                    completed: true,
                },
                {
                    status: "analyzing",
                    order: 2,
                    completed: false,
                },
                {
                    status: "fetching",
                    order: 3,
                    completed: false,
                },
                {
                    status: "clustering",
                    order: 4,
                    completed: false,
                },
                {
                    status: "enriching",
                    order: 5,
                    completed: false,
                },
                {
                    status: "completed",
                    order: 6,
                    completed: false,
                },
                {
                    status: "failed",
                    order: 7,
                    completed: false,
                },
            ],
        });
    });

    test("getJobStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/status/job_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobStatus({
                job_id: "job_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getJobStatus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/status/job_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobStatus({
                job_id: "job_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("getUserJobs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                total: 47,
                page: 1,
                page_size: 10,
                total_pages: 5,
                jobs: [
                    {
                        job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
                        query: "AI company acquisitions",
                        created_at: "2026-02-01T14:30:00Z",
                        status: "completed",
                    },
                ],
            },
        ];
        server
            .mockEndpoint()
            .get("/catchAll/jobs/user")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getUserJobs();
        expect(response).toEqual([
            {
                total: 47,
                page: 1,
                page_size: 10,
                total_pages: 5,
                jobs: [
                    {
                        job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
                        query: "AI company acquisitions",
                        created_at: "2026-02-01T14:30:00Z",
                        status: "completed",
                    },
                ],
            },
        ]);
    });

    test("getUserJobs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/jobs/user")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getUserJobs();
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getJobResults (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            job_id: "job_id",
            query: "Tech company earnings this quarter.",
            context: "Focus on revenue and profit margins.",
            validators: ["is_current_quarter", "contains_financial_data"],
            enrichments: ["company_name", "quarter_identifier", "revenue", "revenue_change", "profit_margin"],
            status: "completed",
            duration: "15m",
            candidate_records: 3200,
            valid_records: 156,
            progress_validated: 50,
            date_range: { start_date: "2025-09-15T00:00:00Z", end_date: "2025-09-30T23:59:59Z" },
            page: 1,
            total_pages: 1,
            page_size: 1,
            all_records: [
                {
                    record_id: "5262823697790152939",
                    record_title: "Oracle Q1 2026 Earnings Exceed Expectations",
                    enrichment: {
                        record_title: "Oracle Q1 2026 Earnings Exceed Expectations",
                        company_name: "Oracle",
                        quarter_identifier: "Q1 2026",
                        revenue: "$14.9 billion",
                        revenue_change: "up 12%",
                        profit_margin: "42% non-GAAP operating margin",
                    },
                    citations: [
                        {
                            title: "Oracle Reports Strong Q1 2026 Results",
                            link: "https://example.com/article",
                            published_date: "2025-09-26T08:54:20Z",
                        },
                    ],
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/catchAll/pull/af7a26d6-cf0b-458c-a6ed-4b6318c74da3")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getJobResults({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
        });
        expect(response).toEqual({
            job_id: "job_id",
            query: "Tech company earnings this quarter.",
            context: "Focus on revenue and profit margins.",
            validators: ["is_current_quarter", "contains_financial_data"],
            enrichments: ["company_name", "quarter_identifier", "revenue", "revenue_change", "profit_margin"],
            status: "completed",
            duration: "15m",
            candidate_records: 3200,
            valid_records: 156,
            progress_validated: 50,
            date_range: {
                start_date: "2025-09-15T00:00:00Z",
                end_date: "2025-09-30T23:59:59Z",
            },
            page: 1,
            total_pages: 1,
            page_size: 1,
            all_records: [
                {
                    record_id: "5262823697790152939",
                    record_title: "Oracle Q1 2026 Earnings Exceed Expectations",
                    enrichment: {
                        record_title: "Oracle Q1 2026 Earnings Exceed Expectations",
                        company_name: "Oracle",
                        quarter_identifier: "Q1 2026",
                        revenue: "$14.9 billion",
                        revenue_change: "up 12%",
                        profit_margin: "42% non-GAAP operating margin",
                    },
                    citations: [
                        {
                            title: "Oracle Reports Strong Q1 2026 Results",
                            link: "https://example.com/article",
                            published_date: "2025-09-26T08:54:20Z",
                        },
                    ],
                },
            ],
        });
    });

    test("getJobResults (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/pull/job_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobResults({
                job_id: "job_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getJobResults (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/pull/job_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobResults({
                job_id: "job_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });
});
