// This file was auto-generated by Fern from our API Definition.

import * as CatchAllApi from "../../src/api/index";
import { CatchAllApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("JobsClient", () => {
    test("createJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            query: "Tech company earnings this quarter",
            schema: "Company [NAME] earned [REVENUE] in [QUARTER]",
            context: "Focus on revenue and profit margins",
        };
        const rawResponseBody = { job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3" };
        server
            .mockEndpoint()
            .post("/catchAll/submit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.createJob({
            query: "Tech company earnings this quarter",
            schema: "Company [NAME] earned [REVENUE] in [QUARTER]",
            context: "Focus on revenue and profit margins",
        });
        expect(response).toEqual({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
        });
    });

    test("createJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/submit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                query: "query",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("createJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { query: "query" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/catchAll/submit")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.createJob({
                query: "query",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("getJobStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
            status: "analyzing",
            steps: [
                { status: "submitted", order: 1, completed: true },
                { status: "analyzing", order: 2, completed: false },
                { status: "fetching", order: 3, completed: false },
                { status: "clustering", order: 4, completed: false },
                { status: "enriching", order: 5, completed: false },
                { status: "completed", order: 6, completed: false },
                { status: "failed", order: 7, completed: false },
            ],
        };
        server
            .mockEndpoint()
            .get("/catchAll/status/af7a26d6-cf0b-458c-a6ed-4b6318c74da3")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getJobStatus({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
        });
        expect(response).toEqual({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
            status: "analyzing",
            steps: [
                {
                    status: "submitted",
                    order: 1,
                    completed: true,
                },
                {
                    status: "analyzing",
                    order: 2,
                    completed: false,
                },
                {
                    status: "fetching",
                    order: 3,
                    completed: false,
                },
                {
                    status: "clustering",
                    order: 4,
                    completed: false,
                },
                {
                    status: "enriching",
                    order: 5,
                    completed: false,
                },
                {
                    status: "completed",
                    order: 6,
                    completed: false,
                },
                {
                    status: "failed",
                    order: 7,
                    completed: false,
                },
            ],
        });
    });

    test("getJobStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/status/job_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobStatus({
                job_id: "job_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getJobStatus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/status/job_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobStatus({
                job_id: "job_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("getUserJobs", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [{ job_id: "job_id", query: "query" }];
        server
            .mockEndpoint()
            .get("/catchAll/jobs/user")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getUserJobs();
        expect(response).toEqual([
            {
                job_id: "job_id",
                query: "query",
            },
        ]);
    });

    test("getJobResults (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            job_id: "job_id",
            query: "Tech company earnings this quarter.",
            context: "Focus on revenue and profit margins.",
            validators: ["is_current_quarter", "contains_financial_data"],
            status: "job_completed",
            duration: "15m",
            candidate_records: 3200,
            valid_records: 156,
            date_range: { start_date: "2025-09-15T00:00:00Z", end_date: "2025-09-30T23:59:59Z" },
            page: 1,
            total_pages: 1,
            page_size: 1,
            all_records: [
                {
                    record_id: "5262823697790152939",
                    record_title: "Oracle Q1 2026 Earnings Exceed Expectations",
                    enrichment: {
                        record_title: "Oracle Q1 2026 Earnings Exceed Expectations",
                        company_name: "Oracle",
                        quarter_identifier: "Q1 2026",
                        revenue: "$14.9 billion",
                        revenue_change: "up 12%",
                        profit_margin: "42% non-GAAP operating margin",
                    },
                    citations: [
                        {
                            title: "Oracle Reports Strong Q1 2026 Results",
                            link: "https://example.com/article",
                            published_date: "2025-09-26T08:54:20Z",
                        },
                    ],
                },
            ],
        };
        server
            .mockEndpoint()
            .get("/catchAll/pull/af7a26d6-cf0b-458c-a6ed-4b6318c74da3")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.jobs.getJobResults({
            job_id: "af7a26d6-cf0b-458c-a6ed-4b6318c74da3",
        });
        expect(response).toEqual({
            job_id: "job_id",
            query: "Tech company earnings this quarter.",
            context: "Focus on revenue and profit margins.",
            validators: ["is_current_quarter", "contains_financial_data"],
            status: "job_completed",
            duration: "15m",
            candidate_records: 3200,
            valid_records: 156,
            date_range: {
                start_date: "2025-09-15T00:00:00Z",
                end_date: "2025-09-30T23:59:59Z",
            },
            page: 1,
            total_pages: 1,
            page_size: 1,
            all_records: [
                {
                    record_id: "5262823697790152939",
                    record_title: "Oracle Q1 2026 Earnings Exceed Expectations",
                    enrichment: {
                        record_title: "Oracle Q1 2026 Earnings Exceed Expectations",
                        company_name: "Oracle",
                        quarter_identifier: "Q1 2026",
                        revenue: "$14.9 billion",
                        revenue_change: "up 12%",
                        profit_margin: "42% non-GAAP operating margin",
                    },
                    citations: [
                        {
                            title: "Oracle Reports Strong Q1 2026 Results",
                            link: "https://example.com/article",
                            published_date: "2025-09-26T08:54:20Z",
                        },
                    ],
                },
            ],
        });
    });

    test("getJobResults (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/pull/job_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobResults({
                job_id: "job_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getJobResults (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/catchAll/pull/job_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.jobs.getJobResults({
                job_id: "job_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });
});
