// This file was auto-generated by Fern from our API Definition.

import { CatchAllApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MetaClient", () => {
    test("healthCheck", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { healthy: true };
        server.mockEndpoint().get("/health").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.meta.healthCheck();
        expect(response).toEqual({
            healthy: true,
        });
    });

    test("getVersion", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { version: "0.3.8" };
        server.mockEndpoint().get("/version").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.meta.getVersion();
        expect(response).toEqual({
            version: "0.3.8",
        });
    });
});
