// This file was auto-generated by Fern from our API Definition.

import * as CatchAllApi from "../../src/api/index";
import { CatchAllApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MetaClient", () => {
    test("healthCheck", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { healthy: true };

        server.mockEndpoint().get("/health").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.meta.healthCheck();
        expect(response).toEqual(rawResponseBody);
    });

    test("getVersion", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { version: "1.3.1" };

        server.mockEndpoint().get("/version").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.meta.getVersion();
        expect(response).toEqual(rawResponseBody);
    });

    test("getPlanLimits (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            features: [
                {
                    name: "Jobs Concurrency",
                    code: "Jobs_Concurrency",
                    value_type: "integer",
                    value: 20,
                    current_usage: 1,
                },
                {
                    name: "Max Results",
                    code: "Job_Max_Results",
                    value_type: "integer",
                    value: 100000,
                    current_usage: 0,
                },
                {
                    name: "Monthly Granted Credits",
                    code: "monthly_free_credits",
                    value_type: "integer",
                    value: 200000,
                    current_usage: 0,
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/catchAll/user/limits")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.meta.getPlanLimits();
        expect(response).toEqual(rawResponseBody);
    });

    test("getPlanLimits (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/user/limits")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.meta.getPlanLimits();
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });
});
