// This file was auto-generated by Fern from our API Definition.

import * as CatchAllApi from "../../src/api/index";
import { CatchAllApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("MonitorsClient", () => {
    test("listMonitors (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            total: 3,
            page: 1,
            page_size: 100,
            total_pages: 1,
            monitors: [
                {
                    monitor_id: "7f3a8b2c-1e4d-4a5b-9c8d-6e7f8a9b0c1d",
                    reference_job_id: "5f0c9087-85cb-4917-b3c7-e5a5eff73a0c",
                    reference_job_query: "Series B funding rounds for SaaS startups",
                    enabled: true,
                    schedule: "0 12 * * *",
                    schedule_human_readable: "Every day at 12 PM",
                    timezone: "UTC",
                    created_at: "2026-02-24T14:00:00Z",
                    webhook: { url: "https://example.com/webhook", method: "POST" },
                    user_key: "***...a1b2",
                },
            ],
        };

        server.mockEndpoint().get("/catchAll/monitors").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.monitors.listMonitors();
        expect(response).toEqual(rawResponseBody);
    });

    test("listMonitors (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/catchAll/monitors").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.monitors.listMonitors();
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("listMonitors (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/catchAll/monitors").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.monitors.listMonitors();
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("createMonitor (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            reference_job_id: "5f0c9087-85cb-4917-b3c7-e5a5eff73a0c",
            schedule: "every day at 12 PM UTC",
            webhook: {
                url: "https://your-endpoint.com/webhook",
                method: "POST",
                headers: { Authorization: "Bearer your_token_here" },
            },
            limit: 10,
            backfill: true,
        };
        const rawResponseBody = {
            monitor_id: "7f3a8b2c-1e4d-4a5b-9c8d-6e7f8a9b0c1d",
            status: "Monitor Created Successfully",
        };

        server
            .mockEndpoint()
            .post("/catchAll/monitors/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.monitors.createMonitor({
            reference_job_id: "5f0c9087-85cb-4917-b3c7-e5a5eff73a0c",
            schedule: "every day at 12 PM UTC",
            webhook: {
                url: "https://your-endpoint.com/webhook",
                method: "POST",
                headers: {
                    Authorization: "Bearer your_token_here",
                },
            },
            limit: 10,
            backfill: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createMonitor (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { reference_job_id: "reference_job_id", schedule: "schedule" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/monitors/create")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.createMonitor({
                reference_job_id: "reference_job_id",
                schedule: "schedule",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("pullMonitorResults (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            monitor_id: "7f3a8b2c-1e4d-4a5b-9c8d-6e7f8a9b0c1d",
            cron_expression: "0 12 * * *",
            timezone: "UTC",
            reference_job: {
                query: "Series B funding rounds for SaaS startups",
                context: "Focus on funding amount and company name",
            },
            run_info: { first_run: "2025-10-23T12:00:00Z", last_run: "2025-11-07T12:00:00Z" },
            records: 487,
            status: "Done",
            all_records: [
                {
                    record_id: "6983973854314692457",
                    record_title: "VulnCheck Raises $25M Series B Funding",
                    enrichment: {
                        funding_amount: 25000000,
                        funding_currency: "USD",
                        funding_date: "2026-02-17",
                        investee_company: {
                            source_text: "VulnCheck",
                            confidence: 0.99,
                            metadata: { name: "VulnCheck", domain_url: "vulncheck.com", domain_url_confidence: "high" },
                        },
                        investor_company: {
                            source_text: "Sorenson Capital",
                            confidence: 0.99,
                            metadata: { name: "Sorenson Capital" },
                        },
                        valuation: 25000000,
                        other_investors: "National Grid Partners, Ten Eleven Ventures, In-Q-Tel",
                        enrichment_confidence: "high",
                    },
                    citations: [
                        {
                            title: "Exclusive: VulnCheck raises $25M funding to help companies patch software bugs",
                            link: "https://www.msn.com/en-us/money/other/exclusive-vulncheck-raises-25m-funding-to-help-companies-patch-software-bugs/ar-AA1WwdjW",
                            published_date: "2026-02-17T14:01:05Z",
                            id: "8760624448e9815f9fb4abd114c75e76",
                            job_id: "6269aa54-c332-4fff-8a65-0d4e82a365e8",
                            added_on: "2025-11-14T21:00:00Z",
                        },
                    ],
                    added_on: "2025-11-14T21:00:00Z",
                    updated_on: "2025-11-14T21:00:00Z",
                },
            ],
            limit: 100,
        };

        server
            .mockEndpoint()
            .get("/catchAll/monitors/pull/monitor_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.monitors.pullMonitorResults({
            monitor_id: "monitor_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("pullMonitorResults (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/monitors/pull/monitor_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.pullMonitorResults({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("pullMonitorResults (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/monitors/pull/monitor_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.pullMonitorResults({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("listMonitorJobs (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            monitor_id: "monitor_id",
            sort_order: "asc",
            total_jobs: 1,
            jobs: [{ job_id: "job_id", start_date: "2025-11-14T21:00:00Z", end_date: "2025-11-15T00:00:00Z" }],
        };

        server
            .mockEndpoint()
            .get("/catchAll/monitors/monitor_id/jobs")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.monitors.listMonitorJobs({
            monitor_id: "monitor_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listMonitorJobs (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/monitors/monitor_id/jobs")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.listMonitorJobs({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("listMonitorJobs (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/monitors/monitor_id/jobs")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.listMonitorJobs({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("enableMonitor (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { backfill: true };
        const rawResponseBody = { success: true, message: "Monitor enabled successfully.", monitor_id: "monitor_id" };

        server
            .mockEndpoint()
            .post("/catchAll/monitors/monitor_id/enable")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.monitors.enableMonitor({
            monitor_id: "monitor_id",
            backfill: true,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("enableMonitor (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/monitors/monitor_id/enable")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.enableMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("enableMonitor (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/monitors/monitor_id/enable")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.enableMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("enableMonitor (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/monitors/monitor_id/enable")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.enableMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("disableMonitor (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "Monitor disabled successfully.", monitor_id: "monitor_id" };

        server
            .mockEndpoint()
            .post("/catchAll/monitors/monitor_id/disable")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.monitors.disableMonitor({
            monitor_id: "monitor_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("disableMonitor (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/monitors/monitor_id/disable")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.disableMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("disableMonitor (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/monitors/monitor_id/disable")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.disableMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("disableMonitor (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/monitors/monitor_id/disable")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.disableMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("updateMonitor (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            webhook: {
                url: "https://new-endpoint.com/webhook",
                method: "POST",
                headers: { Authorization: "Bearer new_token_xyz" },
            },
        };
        const rawResponseBody = {
            monitor_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
            status: "Monitor updated Successfully",
        };

        server
            .mockEndpoint()
            .patch("/catchAll/monitors/monitor_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.monitors.updateMonitor({
            monitor_id: "monitor_id",
            webhook: {
                url: "https://new-endpoint.com/webhook",
                method: "POST",
                headers: {
                    Authorization: "Bearer new_token_xyz",
                },
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateMonitor (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/monitors/monitor_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.updateMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("updateMonitor (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/monitors/monitor_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.updateMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("updateMonitor (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/monitors/monitor_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.monitors.updateMonitor({
                monitor_id: "monitor_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });
});
