// This file was auto-generated by Fern from our API Definition.

import * as CatchAllApi from "../../src/api/index";
import { CatchAllApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ProjectsClient", () => {
    test("listProjects (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            total: 2,
            page: 1,
            page_size: 100,
            total_pages: 1,
            projects: [
                {
                    project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
                    name: "AI M&A Tracking",
                    description: "Tracks AI-related M&A activity.",
                    resources_count: 4,
                    created_at: "2026-05-20T14:31:35Z",
                    updated_at: "2026-05-20T14:31:35Z",
                },
            ],
        };

        server.mockEndpoint().get("/catchAll/projects").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.projects.listProjects({
            search: "M&A",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listProjects (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/catchAll/projects").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("listProjects (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/catchAll/projects").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.projects.listProjects();
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("createProject (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "AI M&A Tracking",
            description: "Tracks AI-related M&A activity for our investment team.",
        };
        const rawResponseBody = {
            success: true,
            message: "Project created successfully.",
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
            name: "AI M&A Tracking",
        };

        server
            .mockEndpoint()
            .post("/catchAll/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.createProject({
            name: "AI M&A Tracking",
            description: "Tracks AI-related M&A activity for our investment team.",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createProject (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "x",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("createProject (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/projects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.createProject({
                name: "x",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("getProject (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            message: "OK",
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
            name: "AI M&A Tracking",
            description: "Tracks AI-related M&A activity for our investment team.",
            resources_count: 4,
            created_at: "2026-05-20T14:31:35Z",
            updated_at: "2026-05-20T14:31:35Z",
        };

        server
            .mockEndpoint()
            .get("/catchAll/projects/60a85db4-78ec-4b78-876a-bc7d9cdadd04")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProject({
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getProject (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/projects/project_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getProject (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/projects/project_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProject({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("deleteProject (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/catchAll/projects/60a85db4-78ec-4b78-876a-bc7d9cdadd04")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.projects.deleteProject({
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteProject (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/projects/project_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("deleteProject (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/projects/project_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.deleteProject({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("updateProject (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "AI M&A Tracking (Q2 2026)" };
        const rawResponseBody = {
            success: true,
            message: "Project updated successfully.",
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
        };

        server
            .mockEndpoint()
            .patch("/catchAll/projects/60a85db4-78ec-4b78-876a-bc7d9cdadd04")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.updateProject({
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
            name: "AI M&A Tracking (Q2 2026)",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateProject (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/projects/project_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.updateProject({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("updateProject (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/projects/project_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.updateProject({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("updateProject (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/projects/project_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.updateProject({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("getProjectOverview (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
            overview: {
                jobs: { key: "value" },
                monitors: { key: "value" },
                datasets: { total: 2 },
                monitor_groups: { total: 0 },
                webhooks: { total: 1 },
            },
        };

        server
            .mockEndpoint()
            .get("/catchAll/projects/60a85db4-78ec-4b78-876a-bc7d9cdadd04/overview")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.getProjectOverview({
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getProjectOverview (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/projects/project_id/overview")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectOverview({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getProjectOverview (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/projects/project_id/overview")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.getProjectOverview({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("listProjectResources (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            total: 1,
            page: 1,
            page_size: 100,
            total_pages: 1,
            resources: [
                {
                    resource_type: "job",
                    resource_id: "48421e16-1f50-4048-b62c-d3bc0789d30d",
                    name: "Series B fintech funding rounds",
                    created_at: "2026-05-20T14:31:37Z",
                    metadata: { key: "value" },
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/catchAll/projects/60a85db4-78ec-4b78-876a-bc7d9cdadd04/resources")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.listProjectResources({
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listProjectResources (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/projects/project_id/resources")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjectResources({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("listProjectResources (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/projects/project_id/resources")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjectResources({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("listProjectResources (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/projects/project_id/resources")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.listProjectResources({
                project_id: "project_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("addResourceToProject (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            resources: [{ resource_type: "job", resource_id: "48421e16-1f50-4048-b62c-d3bc0789d30d" }],
        };
        const rawResponseBody = {
            success: true,
            message: "Resources added to project.",
            results: [
                {
                    resource_type: "job",
                    resource_id: "48421e16-1f50-4048-b62c-d3bc0789d30d",
                    success: true,
                    message: "Resource added to project.",
                    already_exists: false,
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/catchAll/projects/60a85db4-78ec-4b78-876a-bc7d9cdadd04/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.addResourceToProject({
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
            resources: [
                {
                    resource_type: "job",
                    resource_id: "48421e16-1f50-4048-b62c-d3bc0789d30d",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("addResourceToProject (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            resources: [
                { resource_type: "job", resource_id: "resource_id" },
                { resource_type: "job", resource_id: "resource_id" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/catchAll/projects/project_id/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.addResourceToProject({
                project_id: "project_id",
                resources: [
                    {
                        resource_type: "job",
                        resource_id: "resource_id",
                    },
                    {
                        resource_type: "job",
                        resource_id: "resource_id",
                    },
                ],
            });
        }).rejects.toThrow(CatchAllApi.BadRequestError);
    });

    test("addResourceToProject (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            resources: [
                { resource_type: "job", resource_id: "resource_id" },
                { resource_type: "job", resource_id: "resource_id" },
            ],
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/projects/project_id/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.addResourceToProject({
                project_id: "project_id",
                resources: [
                    {
                        resource_type: "job",
                        resource_id: "resource_id",
                    },
                    {
                        resource_type: "job",
                        resource_id: "resource_id",
                    },
                ],
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("addResourceToProject (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            resources: [
                { resource_type: "job", resource_id: "resource_id" },
                { resource_type: "job", resource_id: "resource_id" },
            ],
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/projects/project_id/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.addResourceToProject({
                project_id: "project_id",
                resources: [
                    {
                        resource_type: "job",
                        resource_id: "resource_id",
                    },
                    {
                        resource_type: "job",
                        resource_id: "resource_id",
                    },
                ],
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("removeResourceFromProject (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { success: true, message: "Resource removed from project." };

        server
            .mockEndpoint()
            .delete(
                "/catchAll/projects/60a85db4-78ec-4b78-876a-bc7d9cdadd04/resources/job/48421e16-1f50-4048-b62c-d3bc0789d30d",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.projects.removeResourceFromProject({
            project_id: "60a85db4-78ec-4b78-876a-bc7d9cdadd04",
            resource_type: "job",
            resource_id: "48421e16-1f50-4048-b62c-d3bc0789d30d",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("removeResourceFromProject (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/projects/project_id/resources/job/resource_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.removeResourceFromProject({
                project_id: "project_id",
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("removeResourceFromProject (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/projects/project_id/resources/job/resource_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.projects.removeResourceFromProject({
                project_id: "project_id",
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });
});
