// This file was auto-generated by Fern from our API Definition.

import * as CatchAllApi from "../../src/api/index";
import { CatchAllApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("listWebhooks (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            total: 2,
            page: 1,
            page_size: 100,
            total_pages: 1,
            webhooks: [
                {
                    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    name: "Layoffs Alert",
                    url: "https://hooks.slack.com/services/T000/B000/xxx",
                    type: "slack",
                    delivery_mode: "full",
                    method: "POST",
                    headers: { key: "value" },
                    params: { key: "value" },
                    is_active: true,
                    organization_id: "org-uuid-here",
                    created_by_user_id: "user-uuid-here",
                    created_at: "2026-05-18T10:00:00Z",
                    updated_at: "2026-05-18T10:00:00Z",
                },
                {
                    id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                    name: "M&A Tracker",
                    url: "https://my-service.example.com/catchall-hook",
                    type: "generic",
                    delivery_mode: "per_record",
                    method: "POST",
                    headers: { Authorization: "Bearer token123" },
                    params: { key: "value" },
                    is_active: true,
                    organization_id: "org-uuid-here",
                    created_by_user_id: "user-uuid-here",
                    created_at: "2026-05-19T09:00:00Z",
                    updated_at: "2026-05-19T09:00:00Z",
                },
            ],
        };

        server.mockEndpoint().get("/catchAll/webhooks").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.listWebhooks();
        expect(response).toEqual(rawResponseBody);
    });

    test("listWebhooks (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/catchAll/webhooks").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("listWebhooks (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server.mockEndpoint().get("/catchAll/webhooks").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.listWebhooks();
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("createWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "Layoffs Alert",
            url: "https://hooks.slack.com/services/T000/B000/xxx",
            type: "slack",
            delivery_mode: "full",
        };
        const rawResponseBody = {
            success: true,
            message: "Webhook created successfully.",
            webhook: {
                id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                name: "Layoffs Alert",
                url: "https://hooks.slack.com/services/T000/B000/xxx",
                type: "slack",
                delivery_mode: "full",
                method: "POST",
                headers: { key: "value" },
                params: { key: "value" },
                is_active: true,
                organization_id: "org-uuid-here",
                created_by_user_id: "user-uuid-here",
                created_at: "2026-05-18T10:00:00Z",
                updated_at: "2026-05-18T10:00:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/catchAll/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.createWebhook({
            name: "Layoffs Alert",
            url: "https://hooks.slack.com/services/T000/B000/xxx",
            type: "slack",
            delivery_mode: "full",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.createWebhook({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("createWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name", url: "url" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhooks")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.createWebhook({
                name: "name",
                url: "url",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("getWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            success: true,
            message: "Webhook retrieved successfully.",
            webhook: {
                id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                name: "Layoffs Alert",
                url: "https://hooks.slack.com/services/T000/B000/xxx",
                type: "slack",
                delivery_mode: "full",
                method: "POST",
                headers: { key: "value" },
                params: { key: "value" },
                is_active: true,
                organization_id: "org-uuid-here",
                created_by_user_id: "user-uuid-here",
                created_at: "2026-05-18T10:00:00Z",
                updated_at: "2026-05-18T10:00:00Z",
            },
        };

        server
            .mockEndpoint()
            .get("/catchAll/webhooks/a1b2c3d4-e5f6-7890-abcd-ef1234567890")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.getWebhook({
            webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhooks/webhook_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhooks/webhook_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("getWebhook (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhooks/webhook_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.getWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("deleteWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete("/catchAll/webhooks/a1b2c3d4-e5f6-7890-abcd-ef1234567890")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.webhooks.deleteWebhook({
            webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/webhooks/webhook_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("deleteWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/webhooks/webhook_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.deleteWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("updateWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "Layoffs Alert (EU)", is_active: false };
        const rawResponseBody = {
            success: true,
            message: "Webhook updated successfully.",
            webhook: {
                id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                name: "Layoffs Alert (EU)",
                url: "https://hooks.slack.com/services/T000/B111/yyyy",
                type: "slack",
                delivery_mode: "full",
                method: "POST",
                headers: { key: "value" },
                params: { key: "value" },
                is_active: true,
                organization_id: "org-uuid-here",
                created_by_user_id: "user-uuid-here",
                created_at: "2026-05-18T10:00:00Z",
                updated_at: "2026-05-19T08:30:00Z",
            },
        };

        server
            .mockEndpoint()
            .patch("/catchAll/webhooks/a1b2c3d4-e5f6-7890-abcd-ef1234567890")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.updateWebhook({
            webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            name: "Layoffs Alert (EU)",
            is_active: false,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/webhooks/webhook_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.updateWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("updateWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/webhooks/webhook_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.updateWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("updateWebhook (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/catchAll/webhooks/webhook_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.updateWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("testWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { payload: { test: true, message: "CatchAll webhook test" } };
        const rawResponseBody = {
            success: true,
            message: "Test delivery succeeded.",
            http_status_code: 200,
            response_body: "ok",
        };

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/a1b2c3d4-e5f6-7890-abcd-ef1234567890/test")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.testWebhook({
            webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            payload: {
                test: true,
                message: "CatchAll webhook test",
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("testWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/webhook_id/test")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.testWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("testWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/webhook_id/test")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.testWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("testWebhook (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/webhook_id/test")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.testWebhook({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("listWebhookResources (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            total: 1,
            page: 1,
            page_size: 100,
            total_pages: 1,
            resources: [
                {
                    id: "f1e2d3c4-b5a6-7890-abcd-ef1234567890",
                    webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    resource_type: "monitor",
                    resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
                    assigned_at: "2026-05-18T10:00:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/catchAll/webhooks/a1b2c3d4-e5f6-7890-abcd-ef1234567890/resources")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.listWebhookResources({
            webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listWebhookResources (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhooks/webhook_id/resources")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.listWebhookResources({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("listWebhookResources (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhooks/webhook_id/resources")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.listWebhookResources({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("listWebhookResources (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhooks/webhook_id/resources")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.listWebhookResources({
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("assignWebhookResource (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { resource_type: "monitor", resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4" };
        const rawResponseBody = {
            success: true,
            message: "Resource assigned to webhook.",
            already_existed: false,
            mapping: {
                id: "f1e2d3c4-b5a6-7890-abcd-ef1234567890",
                webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                resource_type: "monitor",
                resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
                assigned_at: "2026-05-18T10:00:00Z",
            },
        };

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/a1b2c3d4-e5f6-7890-abcd-ef1234567890/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.assignWebhookResource({
            webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            resource_type: "monitor",
            resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("assignWebhookResource (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { resource_type: "job", resource_id: "resource_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/webhook_id/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.assignWebhookResource({
                webhook_id: "webhook_id",
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.BadRequestError);
    });

    test("assignWebhookResource (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { resource_type: "job", resource_id: "resource_id" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/webhook_id/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.assignWebhookResource({
                webhook_id: "webhook_id",
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("assignWebhookResource (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { resource_type: "job", resource_id: "resource_id" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/webhook_id/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.assignWebhookResource({
                webhook_id: "webhook_id",
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("assignWebhookResource (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { resource_type: "job", resource_id: "resource_id" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhooks/webhook_id/resources")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.assignWebhookResource({
                webhook_id: "webhook_id",
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("removeWebhookResource (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .delete(
                "/catchAll/webhooks/a1b2c3d4-e5f6-7890-abcd-ef1234567890/resources/job/3fec5b07-8786-46d7-9486-d43ff67eccd4",
            )
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.webhooks.removeWebhookResource({
            webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            resource_type: "job",
            resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
        });
        expect(response).toEqual(undefined);
    });

    test("removeWebhookResource (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/webhooks/webhook_id/resources/job/resource_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.removeWebhookResource({
                webhook_id: "webhook_id",
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("removeWebhookResource (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/catchAll/webhooks/webhook_id/resources/job/resource_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.removeWebhookResource({
                webhook_id: "webhook_id",
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("listWebhooksForResource (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            total: 1,
            page: 1,
            page_size: 100,
            total_pages: 1,
            webhooks: [
                {
                    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    name: "Layoffs Alert",
                    url: "https://hooks.slack.com/services/T000/B000/xxx",
                    type: "slack",
                    delivery_mode: "full",
                    method: "POST",
                    headers: { key: "value" },
                    params: { key: "value" },
                    is_active: true,
                    organization_id: "org-uuid-here",
                    created_by_user_id: "user-uuid-here",
                    created_at: "2026-05-18T10:00:00Z",
                    updated_at: "2026-05-18T10:00:00Z",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/catchAll/resources/job/3fec5b07-8786-46d7-9486-d43ff67eccd4/webhooks")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.listWebhooksForResource({
            resource_type: "job",
            resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listWebhooksForResource (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/resources/job/resource_id/webhooks")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.listWebhooksForResource({
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("listWebhooksForResource (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/resources/job/resource_id/webhooks")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.listWebhooksForResource({
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("listWebhooksForResource (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/resources/job/resource_id/webhooks")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.listWebhooksForResource({
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("triggerWebhook (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .post("/catchAll/webhook/trigger/job/3fec5b07-8786-46d7-9486-d43ff67eccd4")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.webhooks.triggerWebhook({
            resource_type: "job",
            resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
            webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            job_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
        });
        expect(response).toEqual(undefined);
    });

    test("triggerWebhook (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhook/trigger/job/resource_id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.triggerWebhook({
                resource_type: "job",
                resource_id: "resource_id",
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("triggerWebhook (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhook/trigger/job/resource_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.triggerWebhook({
                resource_type: "job",
                resource_id: "resource_id",
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("triggerWebhook (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/catchAll/webhook/trigger/job/resource_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.triggerWebhook({
                resource_type: "job",
                resource_id: "resource_id",
                webhook_id: "webhook_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });

    test("getWebhookDeliveryHistory (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            resource_type: "monitor",
            resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
            total: 2,
            page: 1,
            page_size: 50,
            total_pages: 1,
            items: [
                {
                    id: 42,
                    webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    resource_type: "monitor",
                    resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
                    additional_info: { key: "value" },
                    status_code: 200,
                    attempt_number: 1,
                    timestamp: "2026-05-18T10:00:00Z",
                    delivery_status: "SUCCESS",
                },
                {
                    id: 41,
                    webhook_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                    resource_type: "monitor",
                    resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
                    additional_info: { key: "value" },
                    status_code: 503,
                    attempt_number: 1,
                    timestamp: "2026-05-17T10:00:00Z",
                    delivery_status: "FAILED",
                    error_message: "Service unavailable",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/catchAll/webhook-history")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.getWebhookDeliveryHistory({
            resource_type: "job",
            resource_id: "3fec5b07-8786-46d7-9486-d43ff67eccd4",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getWebhookDeliveryHistory (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhook-history")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.getWebhookDeliveryHistory({
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.ForbiddenError);
    });

    test("getWebhookDeliveryHistory (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhook-history")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.getWebhookDeliveryHistory({
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.NotFoundError);
    });

    test("getWebhookDeliveryHistory (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new CatchAllApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/catchAll/webhook-history")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.webhooks.getWebhookDeliveryHistory({
                resource_type: "job",
                resource_id: "resource_id",
            });
        }).rejects.toThrow(CatchAllApi.UnprocessableEntityError);
    });
});
