// This file was auto-generated by Fern from our API Definition.

export const CatchAllApiEnvironment = {
    Default: "https://catchall.newscatcherapi.com",
} as const;

export type CatchAllApiEnvironment = typeof CatchAllApiEnvironment.Default;
